const $=id=>document.getElementById(id);
const people={nurse:{label:'护士林晓',need:'med',safe:true,clue:'胸牌和避难所名单一致',talk:'诊所的退烧药用完了。'},repairman:{label:'修理工老周',need:'water',safe:true,clue:'工具箱里是卷帘门零件',talk:'给我水，我帮你修门。'},girl:{label:'地图女孩阿梨',need:'food',safe:true,clue:'地图背面画着补给仓坐标',talk:'我用地图换一罐吃的。'},trader:{label:'灰帽商人',need:'water',safe:false,clue:'购物篮底藏着撬锁器',talk:'高价买水，别问我要去哪。'},injured:{label:'受伤旅客',need:'med',safe:false,clue:'绷带下的伤口边缘发黑',talk:'只是擦伤，药卖给我。'}};
const nights=[
 {name:'雨夜开张',goal:55,story:'撑过第一夜，让附近的人知道这里还亮着。',event:'普通顾客更多。'},
 {name:'停水公告',goal:75,story:'城市供水中断，净水成了最贵的东西。',event:'净水售价翻倍。'},
 {name:'诊所求援',goal:85,story:'林晓请求保留药品，救助会影响最终结局。',event:'护士必定出现。'},
 {name:'劫匪踩点',goal:95,story:'有人在观察店门，错误交易会损坏店铺。',event:'危险顾客增加。'},
 {name:'仓库坐标',goal:110,story:'阿梨的地图可能带你找到大批物资。',event:'帮助阿梨可补充库存。'},
 {name:'黑雨封锁',goal:125,story:'感染警报响起，今晚每个决定都更危险。',event:'电力消耗加快。'},
 {name:'最后撤离',goal:150,story:'撤离车午夜抵达。守住店铺，带幸存者离开。',event:'最终夜，无人可以重来。'}];
let base={day:1,cash:80,food:8,water:8,med:4,wall:60,power:70,rep:10,time:18,revenue:0,up:{scanner:0,generator:0,shelf:0},helped:0};
try{Object.assign(base,JSON.parse(localStorage.getItem('lastLightSave')||'{}'))}catch{}let s={...base,queue:[],active:[],running:true,id:1,inspected:false};
function cfg(){return nights[Math.min(s.day-1,nights.length-1)]}function save(){let o={};['day','cash','food','water','med','wall','power','rep','up','helped'].forEach(k=>o[k]=s[k]);localStorage.setItem('lastLightSave',JSON.stringify(o))}
function render(){for(let k of ['day','cash','food','water','med','wall'])$(k).textContent=Math.round(s[k]);$('stockText').textContent=(s.food+s.water+s.med);$('powerText').textContent=Math.round(s.power)+'%';$('repText').textContent=s.rep;$('timeText').textContent=String(Math.floor(s.time)).padStart(2,'0')+':'+(s.time%1>=.5?'30':'00');$('goal').textContent=`${s.revenue} / ${cfg().goal}`;$('goalBar').style.width=Math.min(100,s.revenue/cfg().goal*100)+'%';$('blackout').classList.toggle('on',s.power<8)}
function msg(t){$('message').textContent=t}function prompt(t){$('prompt').textContent=t;$('prompt').classList.add('show');setTimeout(()=>$('prompt').classList.remove('show'),1800)}function door(){$('door').classList.add('open');setTimeout(()=>$('door').classList.remove('open'),900)}
function move(c,l,t,h,ms=2500){c.el.style.transitionDuration=ms+'ms';c.el.style.left=l+'%';c.el.style.top=t+'%';c.el.style.height=h+'px'}
function chooseKind(){if(s.day===3&&!s.active.some(x=>x.kind==='nurse'))return'nurse';if(s.day===5&&!s.active.some(x=>x.kind==='girl'))return'girl';let pool=s.day>=4?['nurse','repairman','girl','trader','injured','trader']:['nurse','repairman','girl','trader','injured'];return pool[Math.floor(Math.random()*pool.length)]}
function spawn(){if(!s.running||s.active.length>=3)return;let kind=chooseKind(),p=people[kind],el=document.createElement('img'),c={id:s.id++,kind,...p,el,value:10+Math.floor(Math.random()*10)};if(s.day===2&&c.need==='water')c.value*=2;el.className='person walking';el.src=`assets/fp/${kind}.webp`;el.alt=p.label;$('people').appendChild(el);s.active.push(c);door();prompt('门铃响了……');setTimeout(()=>move(c,Math.random()>.5?30:70,38,190),500);setTimeout(()=>{el.classList.remove('walking');el.classList.add('shopping')},2600);setTimeout(()=>queue(c),3900)}
function queue(c){if(!s.active.includes(c))return;c.el.classList.remove('shopping');s.queue.push(c);layout();msg(`${c.label}：“${c.talk}” 需要${{food:'罐头',water:'净水',med:'药品'}[c.need]}。`)}
function layout(){s.queue.forEach((c,i)=>{c.el.classList.add('walking');if(i===0){c.el.classList.add('at-counter');move(c,50,22,410,1800)}else{c.el.classList.remove('at-counter');move(c,50+(i%2?12:-12),39,190-i*15,1500)}})}
function resolve(c,accepted){s.queue.shift();let good=accepted===c.safe;if(accepted){if(s[c.need]<=0){msg('库存不足，无法成交。');s.queue.unshift(c);return}s[c.need]--;s.cash+=c.value;s.revenue+=c.value;if(!c.safe){s.wall-=12;s.rep-=2;prompt('危险！店门遭到破坏')}else{s.rep++;if(c.kind==='nurse'||c.kind==='girl')s.helped++}}else{if(c.safe)s.rep--;else{s.rep++;prompt('你避开了一次危险')}}msg(good?'判断正确。'+(accepted?`收入 ¥${c.value}`:'可疑者离开了。'):'判断失误，后果会延续到后面。');exit(c);s.inspected=false;setTimeout(layout,400);render();checkFail()}
function exit(c){c.el.classList.remove('at-counter');move(c,50,38,100,1300);setTimeout(()=>{door();c.el.remove();s.active=s.active.filter(x=>x!==c)},1700)}
function inspect(){let c=s.queue[0];if(!c)return msg('暂时没人站在柜台前。');if(s.power<4)return msg('灯太暗，看不清细节。');s.power-=3;s.inspected=true;msg(`检查结果：${c.clue}。风险判断：${c.safe?'较低':'很高'}。`);render()}
function serve(){let c=s.queue[0];if(!c)return msg('收银台前没人。');$('scanner').classList.add('fire');setTimeout(()=>$('scanner').classList.remove('fire'),600);resolve(c,true)}function refuse(){let c=s.queue[0];if(!c)return msg('没有需要拒绝的顾客。');resolve(c,false)}
function restock(){if(s.cash<15)return msg('现金不足。');s.cash-=15;let n=2+s.up.shelf;s.food+=n;s.water+=n;s.med+=1;msg(`补给送达：罐头和净水 +${n}，药品 +1。`);render()}
function power(){if(s.cash<10)return msg('现金不足。');s.cash-=10;s.power=Math.min(100,s.power+30+s.up.generator*10);msg('备用发电机启动。');render()}
function checkFail(){if(s.wall<=0||s.rep<=0){s.running=false;showEnd(true)}}
function showEnd(failed=false){s.running=false;let won=s.revenue>=cfg().goal&&!failed,final=s.day>=7;let title=failed?'便利店失守':final?(won?'撤离车抵达':'最后的灯熄灭'):won?'本夜目标完成':'天亮前勉强关门';let text=`${cfg().story}<br>营业额 ¥${s.revenue} / ${cfg().goal}，店铺耐久 ${Math.max(0,s.wall)}。`;if(final)text+=`<br><span class="ending">${won&&s.helped>=3?'你带着获救的人一起离开。':'你活了下来，但有些人没能等到天亮。'}</span>`;$('modalTitle').textContent=title;$('modalText').innerHTML=text;let box=$('modalClose').parentElement;box.querySelectorAll('.upgrades').forEach(x=>x.remove());if(!final&&!failed){let u=document.createElement('div');u.className='upgrades';u.innerHTML='<button data-u="shelf">扩建仓储 <small>库存补货 +1</small></button><button data-u="generator">改装发电机 <small>发电效率 +10</small></button><button data-u="scanner">情报终端 <small>检查耗电降低</small></button>';box.appendChild(u);u.querySelectorAll('button').forEach(b=>b.onclick=()=>{s.up[b.dataset.u]++;nextNight()});$('modalClose').style.display='none'}else{$('modalClose').style.display='inline-block';$('modalClose').textContent=final?'重新开始':'重新挑战'}$('modal').classList.remove('hidden');save()}
function nextNight(){s.day++;s.time=18;s.revenue=0;s.power=Math.min(100,s.power+25);s.food+=1;s.water+=1;s.running=true;s.queue=[];s.active.forEach(c=>c.el.remove());s.active=[];$('modal').classList.add('hidden');$('modalClose').style.display='inline-block';msg(`第${s.day}夜：${cfg().name}。${cfg().story}`);save();render();spawn()}
function tick(){if(!s.running)return;s.time+=.5;s.power=Math.max(0,s.power-(s.day===6?2.2:1.2));if(Math.random()<.34)spawn();if(s.power===0)s.food=Math.max(0,s.food-.3);if(s.time>=23)showEnd();render()}
$('serve').onclick=serve;$('refuse').onclick=refuse;$('inspect').onclick=inspect;$('restock').onclick=restock;$('power').onclick=power;$('endDay').onclick=()=>showEnd();$('modalClose').onclick=()=>{localStorage.removeItem('lastLightSave');location.reload()};render();msg(`第${s.day}夜：${cfg().name}。${cfg().story}`);setTimeout(spawn,500);setInterval(tick,2400);
