const $=id=>document.getElementById(id),faces=['nurse','repairman','girl','trader','infected'];
let s={day:1,cash:80,stock:72,power:68,rep:12,time:8,revenue:0,queue:[],customers:[],running:true,speed:1,nextId:1};
const paths={entry:[48,9],food:[40,43],daily:[62,45],fridge:[17,42],exit:[49,8]};
function render(){let p=Math.round(s.stock);$('day').textContent=s.day;$('cash').textContent=s.cash;$('stockText').textContent=p+'%';$('powerText').textContent=Math.round(s.power)+'%';$('repText').textContent=s.rep;$('timeText').textContent=String(Math.floor(s.time)).padStart(2,'0')+':'+(s.time%1>=.5?'30':'00');$('queueBadge').textContent=s.queue.length;$('goal').textContent=`营业额 ${s.revenue} / 120`;$('goalBar').style.width=Math.min(100,s.revenue/1.2)+'%';let a=p>55?'full':p>25?'half':'low';$('shelfA').src=`assets/shop/shelf-${a}.webp`;$('shelfB').src=`assets/shop/shelf-${p>40?'half':'low'}.webp`;$('blackout').classList.toggle('on',s.power<=8)}
function pos(el,key){let [x,y]=paths[key];el.style.left=(x-6)+'%';el.style.top=(y-8)+'%'}
function name(k){return({nurse:'护士',repairman:'修理工',girl:'地图女孩',trader:'灰帽商人',infected:'受伤旅客'})[k]}
function spawn(){if(!s.running||s.customers.length>=4)return;let id=s.nextId++,kind=faces[Math.floor(Math.random()*faces.length)],el=document.createElement('img');el.className='customer';el.src=`assets/${kind}.webp`;el.dataset.id=id;$('people').appendChild(el);pos(el,'entry');let c={id,el,kind,item:['food','daily','fridge'][Math.floor(Math.random()*3)],value:8+Math.floor(Math.random()*13)};s.customers.push(c);setTimeout(()=>{pos(el,c.item);el.classList.add('shopping')},100);setTimeout(()=>queue(c),2200/s.speed)}
function queue(c){if(!s.customers.includes(c))return;if(s.queue.length>=3){msg('????????????????');s.rep=Math.max(0,s.rep-1);leave(c,true);return render();}c.el.classList.remove('shopping');let q=s.queue.length;c.el.style.left=(69-q*7)+'%';c.el.style.top=(68-q*3)+'%';s.queue.push(c);msg(`${name(c.kind)}拿好了商品，正在等待结账。`);render()}
function leave(c,bad=false){pos(c.el,'exit');if(bad)c.el.style.filter='grayscale(1)';setTimeout(()=>{c.el.remove();s.customers=s.customers.filter(x=>x!==c)},1800)}
function serve(){let c=s.queue.shift();if(!c)return msg('收银台前暂时没人。');if(s.stock<5){s.rep--;msg('货架空了，顾客失望离开。');leave(c,true);return render()}s.stock-=5;s.cash+=c.value;s.revenue+=c.value;if(Math.random()>.65)s.rep++;float('+'+c.value,76,70);msg(`${name(c.kind)}完成结账，收入 ¥${c.value}。`);leave(c);render()}
function restock(){if(s.cash<15)return msg('现金不足，无法联系补给商。');s.cash-=15;s.stock=Math.min(100,s.stock+28);float('+库存',40,45);msg('伙计把新货推上了货架。');render()}
function power(){if(s.cash<10)return msg('现金不足，买不起燃料。');s.cash-=10;s.power=Math.min(100,s.power+32);float('+电力',16,82);msg('发电机轰鸣起来，灯光稳定了。');render()}
function float(t,x,y){let e=document.createElement('span');e.className='floater';e.textContent=t;e.style.left=x+'%';e.style.top=y+'%';$('floaters').appendChild(e);setTimeout(()=>e.remove(),1300)}function msg(t){$('message').textContent=t}
function event(){let es=[['临时停电','冰柜停止工作，快启动发电机！',()=>s.power=Math.max(0,s.power-28)],['抢购潮','避难所广播引来一批顾客。',()=>{spawn();setTimeout(spawn,300);setTimeout(spawn,600)}],['物资车抵达','临期商品入库，库存 +18。',()=>s.stock=Math.min(100,s.stock+18)],['可疑顾客','有人在货架旁徘徊，口碑 -1。',()=>s.rep=Math.max(0,s.rep-1)]],e=es[Math.floor(Math.random()*es.length)];$('eventBanner').textContent='⚠ '+e[0]+'：'+e[1];$('eventBanner').classList.add('show');e[2]();render();setTimeout(()=>$('eventBanner').classList.remove('show'),2600)}
function finish(){if(!s.running)return;s.running=false;$('modalTitle').textContent=s.revenue>=120?'今晚的灯还亮着':'勉强撑过一天';$('modalText').textContent=`营业额 ¥${s.revenue}，接待 ${s.nextId-1} 位顾客。`;$('modal').classList.remove('hidden')}
function nextDay(){s.day++;s.time=8;s.revenue=0;s.running=true;s.nextId=1;s.queue=[];s.customers.forEach(c=>c.el.remove());s.customers=[];$('modal').classList.add('hidden');msg('卷帘门升起，新的一天开始。');render();spawn()}
function tick(){if(!s.running)return;s.time+=.5;s.power=Math.max(0,s.power-1.1);if(Math.random()<.26)spawn();if(Math.random()<.055)event();if(s.power===0)s.stock=Math.max(0,s.stock-2);if(s.time>=22)finish();render()}
document.querySelectorAll('.zone').forEach(z=>z.onclick=()=>{document.querySelectorAll('.zone').forEach(x=>x.classList.remove('selected'));z.classList.add('selected');msg({food:'食品货架：库存变化会真实切换货架图。',daily:'日用货架：灾后利润较稳定。',fridge:'冰柜：停电后库存会持续损耗。',register:'收银台：及时为排队顾客扫码。',generator:'发电机：花费现金补充燃料。'}[z.dataset.zone])});$('serve').onclick=serve;$('restock').onclick=restock;$('power').onclick=power;$('endDay').onclick=finish;$('modalClose').onclick=nextDay;$('inventory').onclick=()=>msg(`仓库盘点：综合库存 ${Math.round(s.stock)}%。`);$('decor').onclick=()=>msg('改造系统下一阶段开放：招牌、货架、安保门。');$('speed').onclick=()=>{s.speed=s.speed===1?2:1;$('speed').textContent='×'+s.speed};render();spawn();setInterval(tick,2200);
