/* P0/P1 market pass: recovery, Su Yan art, first-session coaching, Night Shift 2.0. */
(()=>{'use strict';if(typeof sceneEl==='undefined'||typeof menu==='undefined')return;
const LC=window.LastLightLocale,L=(z,e)=>LC?.pick?LC.pick(z,e):(document.documentElement.lang.startsWith('en')?e:z),SK='lastLightStory',MK='lastLightMetaV1',NS=Storage.prototype.setItem,NG=Storage.prototype.getItem;
const ok=v=>{try{return !!JSON.parse(v)}catch{return false}};[SK,MK].forEach(k=>{const v=NG.call(localStorage,k);if(v&&!ok(v)){const b=NG.call(localStorage,k+':backup');b&&ok(b)?NS.call(localStorage,k,b):localStorage.removeItem(k)}});
if(!window.__llSafe){window.__llSafe=1;Storage.prototype.setItem=function(k,v){if(this===localStorage&&(k===SK||k===MK)&&ok(v)){const old=NG.call(this,k);if(ok(old))NS.call(this,k+':backup',old)}return NS.call(this,k,v)}}
function norm(){if(typeof s==='undefined'||!s)return;s.flags=s.flags||{};s.found=s.found||{};s.evidence=s.evidence||{};s.talked=s.talked||{};s.line=s.line||{};s.used=s.used||{};if(typeof nodes!=='undefined'&&(!s.node||!nodes[s.node]))s.node='dawn';['food','water','med','battery','trust'].forEach(k=>{s[k]=Number.isFinite(+s[k])?+s[k]:(k==='trust'?0:1)})}
function backup(){try{if(typeof s!=='undefined')NS.call(localStorage,SK+':backup',JSON.stringify(s));const m=NG.call(localStorage,MK);if(ok(m))NS.call(localStorage,MK+':backup',m)}catch{}}norm();backup();setInterval(backup,2e4);addEventListener('pagehide',backup);window.LastLightRecovery={backup,restore(){[SK,MK].forEach(k=>{const b=NG.call(localStorage,k+':backup');if(ok(b))NS.call(localStorage,k,b)});location.reload()}};
const B='assets/story/characters/suyan-western-transparent/webp/',SA={f:B+'suyan-western-fullbody.webp',b:B+'suyan-western-dialogue-bust.webp',m:B+'suyan-western-medicine.webp',s:B+'suyan-western-seated.webp'},actor=document.getElementById('character'),si=new Image();si.className='p0-suyan-art';si.alt='Su Yan';actor?.append(si);Object.values(SA).forEach(src=>{const i=new Image;i.src=src});
function suyan(){if(typeof s==='undefined')return null;const n=nodes?.[s.node],yes=s.node==='c2_suyan'||['苏妍','Su Yan'].includes(n?.speaker);if(!yes)return null;const t=String(typeof n?.text==='function'?n.text(s):n?.text||'').toLowerCase();if(/药|medicine/.test(t))return SA.m;if(s.node==='c2_suyan'&&((s.found?.c2_suyan||[]).length||s.talked?.c2_suyan))return SA.s;if(document.querySelector('.dialogue-playing,.director-caption.show'))return SA.b;return SA.f}
function syncArt(){const src=suyan();actor?.classList.toggle('p0-suyan-visible',!!src);document.body.classList.toggle('p0-has-suyan',!!src);if(src&&!si.src.endsWith(src))si.src=src}si.onerror=()=>actor?.classList.remove('p0-suyan-visible');
const coach=document.createElement('aside');coach.className='p0-coach';coach.innerHTML='<small></small><b></b><p></p><div class="p0-coach-progress"></div><button></button>';sceneEl.append(coach);const toast=document.createElement('div');toast.className='p0-success-toast';sceneEl.append(toast);let tt;
function pop(a,b){clearTimeout(tt);toast.innerHTML=`<b>${a}</b><span>${b}</span>`;toast.classList.add('show');tt=setTimeout(()=>toast.classList.remove('show'),2300)}
function cs(){if(typeof s==='undefined'||s.flags?.p0CoachDone)return null;const all=investigations?.[s.node]?.length||0,got=s.found?.[s.node]?.length||0,person=(dialogues?.[s.node]||[]).length>0,talk=!person||s.talked?.[s.node],has=!!directorCases?.[s.node],done=!has||s.flags?.['case_'+s.node];if(!talk)return[1,L('先听证词','Hear the testimony'),L('点击人物，对话由你主动继续。','Select the person; dialogue waits for you.'),actor];if(got<all)return[2,L('检查异常','Inspect the anomaly'),L('完成两步检查，再判断哪项观察成立。','Complete both steps, then choose the supported observation.'),document.querySelector('#hotspots .hotspot:not(.consumed)')];if(!done)return[3,L('组合证据','Connect the evidence'),L('选择两件证物共同支持的结论。','Choose what both clues prove together.'),document.querySelector('.case-button')];return[4,L('做出决定','Make the call'),L('比较资源、关系与风险。','Weigh resources, relationships and risk.'),document.getElementById('choices')]}
let ps=0;function syncCoach(){const q=cs();if(!q||document.querySelector('.liveops-shell.show,.p1-shell.show'))return coach.classList.remove('show');const[st,title,text,target]=q;coach.querySelector('small').textContent=L('首次调查','FIRST CASE')+' · '+st+'/4';coach.querySelector('b').textContent=title;coach.querySelector('p').textContent=text;coach.querySelector('.p0-coach-progress').innerHTML=[1,2,3,4].map(n=>`<i class="${n<st?'done':n===st?'active':''}"></i>`).join('');const btn=coach.querySelector('button');btn.textContent=L('指给我看','Show me');btn.onclick=()=>{target?.classList.add('p0-coach-target');setTimeout(()=>target?.classList.remove('p0-coach-target'),2200)};coach.classList.add('show');if(ps&&st>ps){if(st===3&&!s.flags.p0FirstClue){s.flags.p0FirstClue=1;if(typeof gainMomentum==='function')gainMomentum(10,L('首条证物','First clue'));pop(L('证物已锁定','Evidence secured'),L('事实来自观察，不是猜测。','The fact came from observation, not guessing.'))}if(st===4&&!s.flags.p0FirstCase){s.flags.p0FirstCase=1;if(typeof gainMomentum==='function')gainMomentum(15,L('首次推理','First deduction'));pop(L('推理成立','Deduction confirmed'),L('现在选择会产生后续后果。','Your choice now creates consequences.'))}try{localStorage.setItem(SK,JSON.stringify(s))}catch{}}ps=st}
document.querySelectorAll('.liveops-menu,.liveops-shell,.liveops-results,.liveops-shop').forEach(x=>{x.classList.add('p1-legacy-liveops');x.setAttribute('aria-hidden','true')});
const DM={credits:80,reputation:0,shifts:0,bestScore:0,streak:0,lastDaily:'',claimedStory:{},upgrades:{pack:0,filter:0,radio:0,lock:0,medkit:0,lamp:0,alarm:0}},load=()=>{try{const x=JSON.parse(localStorage.getItem(MK)||'null')||{};return{...DM,...x,upgrades:{...DM.upgrades,...x.upgrades},claimedStory:{...x.claimedStory}}}catch{return JSON.parse(JSON.stringify(DM))}};let meta=load();
const F=['assets/nurse.webp','assets/repairman.webp','assets/infected.webp','assets/girl.webp','assets/trader.webp','assets/fp/girl.webp','assets/fp/repairman.webp','assets/fp/injured.webp','assets/fp/nurse.webp',SA.b];
const D=[
['medic',1,'林晓','Lin Xiao','诊所医生','Clinic doctor',0,'water','诊所净水只够到天亮，我用配给记录交换。','The clinic has water only until dawn. I can trade ration records.',1,'胸牌匹配诊所记录','Badge matches clinic records','水壶有消毒标记','Bottle has a sterilization mark',15,'她交出真实记录。','She hands over genuine records.',0,0,0],
['repair',1,'老周','Old Zhou','修理工','Repair technician',1,'food','给我罐头，我修好卷帘门。','Give me food and I will repair the shutter.',1,'工具磨损符合工种','Tool wear matches his trade','指出了准确故障点','He identifies the exact fault',12,'卷帘门得到加固。','The shutter is reinforced.',0,10,0],
['infected',1,'无名旅客','Unknown traveler','伤者','Injured traveler',2,'med','只是划伤，给我药。','It is only a cut. Give me medicine.',0,'伤口有黑色网纹','Black webbing surrounds the wound','瞳孔不追随灯光','Pupils do not track light',22,'他撞向柜台。','He lunges at the counter.',16,0,0],
['mapper',1,'阿梨','Ali','测绘员','Surveyor',3,'food','路线图换一份食物。','A route map for one food ration.',1,'积水深度准确','Flood depth is accurate','背包只有测绘工具','Pack contains surveying tools',10,'她留下安全路线。','She leaves a safe route.',0,0,1],
['scout',1,'灰帽商人','Gray Hat','物资贩子','Trader',4,'water','高价换水，别问车在哪。','I pay well for water. Do not ask about my vehicle.',0,'撬棍有新鲜红漆','Crowbar has fresh red paint','门外有三组脚印','Three sets of prints wait outside',25,'他在替车队数人。','He was counting people for raiders.',12,0,0],
['courier',1,'周冉','Zhou Ran','骑手','Courier',5,'water','我知道屋顶连桥。','I know the rooftop bridge.',1,'路线贴纸覆盖多街区','Route stickers cover many blocks','鞋底泥来自后巷','Mud came from the rear alley',13,'她留下撤离路线。','She leaves an escape route.',0,0,1],
['guard',1,'郑凯','Zheng Kai','保安队长','Security captain',6,'food','我需要补给去开消防门。','I need supplies to reopen the fire doors.',1,'对讲机接收商场频道','Radio receives the mall channel','钥匙符合消防门','Key fits a fire door',16,'他送来工具。','He returns with tools.',0,7,0],
['bait',1,'求救者','Distress caller','身份不明','Unknown identity',7,'med','后巷只有我一个人。','I am alone in the alley.',0,'衣服干燥','Clothes are dry','求救节奏与敲门一致','Plea matches the knock pattern',24,'这是诱导开门的暗号。','It is a coded lure.',18,0,0],
['accountant',1,'何秀兰','He Xiulan','会计','Accountant',5,'water','我能看懂白塔配给账。','I can decode White Tower ledgers.',1,'账本有连续核算','Ledger has continuous calculations','指出重复编号','She identifies duplicate IDs',18,'她找出人口评级。','She uncovers population ratings.',0,0,1],
['fakeMedic',1,'巡回护士','Traveling nurse','医疗人员','Medical worker',8,'med','把药全部交给我统一分配。','Give me all medicine for distribution.',0,'急救包没有无菌耗材','No sterile supplies in the bag','胸牌医院早已关闭','Badge hospital closed years ago',28,'她想带走全部药品。','She wants all the medicine.',14,0,0],
['firefighter',1,'程野','Cheng Ye','消防救援','Fire rescuer',6,'water','我能移开堵住后门的架子。','I can clear the rear exit.',1,'手套有液压剪磨痕','Gloves show cutter wear','知道承重墙位置','He knows the load-bearing walls',14,'后门重新打开。','The rear exit reopens.',0,12,0],
['silentCar',1,'车队联络员','Convoy liaison','撤离人员','Evacuation staff',4,'food','先把食物搬出来核验。','Bring the food out for inspection.',0,'车辆没有救援编号','Vehicle has no rescue number','无线电不报呼号','Radio gives no call sign',30,'假车队冲击卷帘门。','The fake convoy attacks.',20,0,0],
['teacher',2,'艾琳','Erin','教师','Teacher',5,'food','地下教室还有六个孩子。','Six children remain in a basement classroom.',1,'名单有六种笔迹','List has six handwritings','带着儿童吸入器','She carries a child inhaler',19,'她留下学校入口。','She leaves the school entrance.',0,0,1],
['wireman',2,'电缆工','Cable worker','维护人员','Maintenance worker',1,'water','我能恢复北区线路。','I can restore the north grid.',0,'钳子有爆破粉尘','Cutters carry explosive dust','工牌编号被磨掉','ID number was sanded away',27,'他在找备用发电机。','He was locating the generator.',15,0,0],
['chemist',2,'罗莎','Rosa','水质化验员','Water analyst',0,'water','净水样本换黑雨检测。','Clean water for a black-rain test.',1,'试纸仍在有效期','Test strips are valid','手套只有酸蚀痕迹','Gloves show acid corrosion',20,'她确认人造示踪剂。','She confirms an artificial tracer.',0,0,2],
['mother',2,'年轻母亲','Young mother','避难者','Refugee',5,'med','孩子发烧，我不进门。','My child has a fever. I will stay outside.',1,'婴儿车轮印连续','Stroller tracks are continuous','体温计显示高热','Thermometer shows a real fever',17,'她保持距离离开。','She keeps her distance.',0,0,0],
['decoyChild',2,'哭泣女孩','Crying girl','失散儿童','Lost child',3,'food','妈妈在街角，我能进去吗？','My mother is nearby. May I come inside?',0,'哭声间隔完全相同','Every sob has identical timing','衣领藏有扬声器','A speaker is hidden in the collar',31,'这是录音假人。','It is a recorded decoy.',22,0,0],
['radioPriest',2,'牧师','Pastor','协调员','Coordinator',4,'food','我登记还亮灯的商店。','I register stores that still have power.',0,'表格只记人数武器','Form records people and weapons','十字架刻着车队编号','Cross carries a convoy number',29,'他向劫掠者传送信息。','He transmits data to raiders.',17,0,0],
['farmer',2,'温室管理员','Greenhouse keeper','种植员','Grower',1,'water','种子换净水。','Seeds for clean water.',1,'种子封装日期不同','Seed packets have different dates','靴底是温室营养土','Boots carry greenhouse soil',18,'种子改善后续补给。','Seeds improve future supplies.',0,0,0],
['suyanVisit',2,'苏妍','Su Yan','白塔逃离者','White Tower defector',9,'med','给我药，我告诉你车队换频时间。','Give me medicine and I will reveal the convoy frequency change.',1,'主动放下定位器','She places the tracker down','频谱与广播跳频一致','Spectrum matches broadcast hops',24,'换频时间是真的。','The timing is genuine.',0,0,2],
['suyanDecoy',3,'苏妍','Su Yan','身份存疑','Identity uncertain',9,'water','你还会再相信我一次，对吧？','You will trust me one more time, right?',0,'定位器仍在发送坐标','Tracker still transmits coordinates','影子旁还有第二个人','A second figure appears in her shadow',38,'伏击者扑向卷帘门。','The ambush team attacks.',25,0,0],
['engineer',3,'许曼','Xu Man','白塔工程师','White Tower engineer',0,'food','我有泵站权限卡。','I have a pump access card.',1,'卡片仍能在线握手','Card still performs a handshake','袖口有泵站防腐剂','Sleeve carries pump sealant',28,'权限卡打开维修通道。','The card opens a service route.',0,8,1],
['collector',3,'遗体回收员','Body collector','市政人员','Municipal worker',2,'med','尸袋拉链划伤了我。','A body-bag zipper cut me.',0,'尸袋内有规律敲击','Regular knocks come from the bag','冷藏机没有启动','Refrigeration is off',36,'感染者冲破束带。','An infected captive breaks free.',28,0,0],
['droneTech',3,'无人机技师','Drone technician','维修承包商','Service contractor',1,'water','我能把这里标成空屋。','I can mark this store as empty.',1,'终端有有效证书','Terminal shows a valid certificate','节点编号为L-17','Display identifies L-17',30,'无人机暂时忽略商店。','Drones temporarily ignore the store.',0,5,2],
['taxOfficer',3,'配给稽核员','Ration inspector','白塔审计','White Tower audit',4,'food','拒绝核验将被标记。','Refusal will flag your store.',0,'表格早于灾难一年','Form predates the disaster','印章左右颠倒','Seal is mirrored',37,'他在套取库存。','He was extracting inventory totals.',20,0,0],
['twins',3,'双胞胎姐妹','Twin sisters','避难者','Refugees',5,'food','我们共用一份口粮。','We will share one ration.',1,'鞋印来自同一巷口','Tracks come from the same alley','家庭信息相互吻合','Family details match',25,'她们帮助整理库存。','They help organize supplies.',0,0,0],
['voiceClone',3,'林晓','Lin Xiao','诊所医生','Clinic doctor',0,'med','快开门，是我。','Open the door, it is me.',0,'声音没有呼吸停顿','Voice has no breathing pauses','胸牌边缘有屏幕像素','Badge edge shows display pixels',42,'门外是语音克隆装置。','A voice-clone device waits outside.',24,0,0],
['soldier',4,'退役军官','Retired officer','街区防卫','District defense',4,'food','我能训练守卫。','I can train your defenders.',1,'旧伤匹配服役记录','Injuries match service records','地图死角可验证','Map blind spots are verifiable',40,'他留下防守方案。','He leaves a defense plan.',0,18,0],
['cleanTeam',4,'净化小队','Decontamination team','白塔防疫','White Tower containment',8,'med','交出全部药品并撤离。','Surrender all medicine and evacuate.',0,'过滤罐没有拆封','Suit filters are unopened','喷雾只有示踪粉','Sprayers contain tracer powder',48,'他们试图标记商店。','They try to mark the store.',32,0,0],
['signalHunter',4,'信号猎人','Signal hunter','独立侦察员','Independent scout',3,'water','我追踪到你姐姐的旧信号。','I traced your sister’s old signal.',1,'录音含校验节奏','Recording contains the checksum rhythm','坐标避开中继站','Route avoids relay stations',45,'她交出真实旧广播。','She provides a genuine old broadcast.',0,0,3]
];
const E=D.map(a=>({id:a[0],tier:a[1],nz:a[2],ne:a[3],rz:a[4],re:a[5],face:F[a[6]],need:a[7],tz:a[8],te:a[9],safe:!!a[10],cz:[a[11],a[13]],ce:[a[12],a[14]],reward:a[15],xz:a[16],xe:a[17],damage:a[18],repair:a[19],focus:a[20]}));
const U={pack:['加固背包','Reinforced Pack','每级 +1 罐头','+1 food per level',70,3],filter:['净水滤芯','Water Filter','每级 +1 净水','+1 water per level',75,3],radio:['短波监听','Shortwave Radio','每级 +1 调查','+1 inspection per level',90,3],lock:['卷帘门锁','Shutter Lock','每级 +10 耐久','+10 shelter per level',100,3],medkit:['急救储备','Medical Cache','每级 +1 药品','+1 medicine per level',110,2],lamp:['检修灯','Inspection Lamp','提高调查奖励','Improves inspected rewards',120,3],alarm:['震动警报','Vibration Alarm','每级减少4点受损','-4 damage per level',135,3]},cost=id=>Math.round(U[id][4]*1.7**(meta.upgrades[id]||0)),save=()=>{localStorage.setItem(MK,JSON.stringify(meta));menu2()};
const lm=document.createElement('div');lm.className='liveops-menu p1-menu';menu.querySelector('.start-card')?.append(lm);const sh=document.createElement('section');sh.className='liveops-shell p1-shell';sceneEl.append(sh);const rs=document.createElement('section');rs.className='liveops-results p1-results';sceneEl.append(rs);const sp=document.createElement('section');sp.className='liveops-shop p1-shop';sceneEl.append(sp);let run;const dk=()=>new Date().toISOString().slice(0,10),tier=()=>Math.min(4,1+Math.floor(meta.shifts/3)+(meta.streak>=5?1:0)),en=()=>document.documentElement.lang.startsWith('en'),lab=(e,k)=>e[k+(en()?'e':'z')],shuffle=(a,seed)=>{let n=[...String(seed)].reduce((x,c)=>(x*33+c.charCodeAt(0))>>>0,2166136261),b=[...a];for(let i=b.length-1;i;i--){n=(n*1664525+1013904223)>>>0;let j=n%(i+1);[b[i],b[j]]=[b[j],b[i]]}return b};
function start(daily=0){meta=load();const t=tier(),rounds=Math.min(8,5+t),up=meta.upgrades,seed=daily?dk():Date.now()+'-'+meta.shifts,pool=E.filter(e=>e.tier<=t);let order=meta.shifts===0&&!daily?['medic','infected','repair','scout','mapper','bait'].map(id=>E.find(e=>e.id===id)):shuffle(pool,seed).slice(0,rounds);run={daily,tier:t,index:0,score:0,correct:0,shelter:50+(up.lock||0)*10,focus:3+(up.radio||0),food:3+(up.pack||0),water:3+(up.filter||0),med:1+(up.medkit||0),order,inspected:0,acted:0};menu.classList.remove('show');sh.classList.add('show');window.LastLightPlatform?.gameplayStart({mode:'night-shift-v2',tier:String(t),round:'1'});draw()}
function draw(){const e=run.order[run.index];sh.innerHTML=`<div class="liveops-top"><div><small>NIGHT SHIFT 2.0 · ${L('难度','TIER')} ${run.tier}</small><h2>${L('最后一盏灯 · 夜班守店','Last Light Mart · Night Shift')}</h2></div><button class="p1-close">${L('返回标题','Back')}</button></div><div class="liveops-stats"><span>${L('回合','ROUND')} <b>${run.index+1}/${run.order.length}</b></span><span>${L('店铺','SHELTER')} <b>${Math.max(0,run.shelter)}</b></span><span>${L('调查','INSPECT')} <b>${run.focus}</b></span><span>${L('罐头','FOOD')} <b>${run.food}</b></span><span>${L('净水','WATER')} <b>${run.water}</b></span><span>${L('药品','MED')} <b>${run.med}</b></span><span>${L('得分','SCORE')} <b>${run.score}</b></span></div><div class="liveops-stage"><img class="liveops-person" src="${e.face}"><div class="liveops-risk evidence-ready">${run.inspected?L('证据已显示','Evidence Revealed'):L('风险未知','Risk Unknown')}</div><div class="liveops-copy"><small class="liveops-role">${lab(e,'r')}</small><h3>${lab(e,'n')}</h3><p class="liveops-dialog">“${lab(e,'t')}”</p><div class="liveops-clues">${run.inspected?(en()?e.ce:e.cz).map(x=>`<span>${x}</span>`).join(''):`<span>${L('调查后才能看到关键细节','Inspect to reveal critical details')}</span>`}</div>${run.inspected?`<p class="liveops-reasoning-note">${L('比较说法与两条证据，再决定交易或关门。','Compare the claim with both clues before deciding.')}</p>`:''}<div class="liveops-actions"><button data-a="i" ${run.inspected||run.focus<=0?'disabled':''}>${run.inspected?L('已经调查','Inspected'):L('调查身份','Inspect')+' · '+run.focus}</button><button data-a="y" class="primary">${L('接受交易','Accept Trade')}</button><button data-a="n">${L('拒绝开门','Keep Door Closed')}</button></div><p class="liveops-result"></p></div></div>`;sh.querySelector('.p1-close').onclick=()=>{sh.classList.remove('show');menu.classList.add('show')};sh.querySelector('[data-a=i]').onclick=()=>{run.focus--;run.inspected=1;draw()};sh.querySelector('[data-a=y]').onclick=()=>resolve(1);sh.querySelector('[data-a=n]').onclick=()=>resolve(0)}
function resolve(accept){if(run.acted)return;const e=run.order[run.index],r=sh.querySelector('.liveops-result');if(accept&&run[e.need]<=0)return r.textContent=L('物资不足。','Not enough stock.');run.acted=1;if(accept)run[e.need]--;const right=(accept&&e.safe)||(!accept&&!e.safe);if(right){run.correct++;run.score+=e.reward+(run.inspected?5+(meta.upgrades.lamp||0)*2:0);run.shelter+=e.repair||0;run.focus+=e.focus||0;r.textContent=L('判断正确：','Correct read: ')+lab(e,'x');if(run.index===0&&meta.shifts===0)pop(L('第一次判断成功','First correct read'),L('你用证据保住了资源。','Evidence protected your resources.'))}else{const dmg=Math.max(0,(e.damage||8)-(meta.upgrades.alarm||0)*4);run.shelter-=dmg;r.textContent=L('判断失误：','Wrong call: ')+lab(e,'x')+' · -'+dmg}sh.querySelectorAll('[data-a]').forEach(b=>b.disabled=1);setTimeout(()=>{run.index++;run.inspected=run.acted=0;run.shelter<=0||run.index>=run.order.length?finish():draw()},1300)}
function finish(){sh.classList.remove('show');window.LastLightPlatform?.gameplayStop();const clear=run.shelter>0,score=run.score+Math.max(0,run.shelter),daily=run.daily&&meta.lastDaily!==dk()?30:0,credits=(clear?22:8)+run.correct*6+Math.floor(run.score/8)+daily+run.tier*3,rep=Math.max(1,run.correct+(clear?2:0)+run.tier-1);meta.shifts++;meta.bestScore=Math.max(meta.bestScore,score);meta.streak=clear?meta.streak+1:0;if(daily)meta.lastDaily=dk();let claimed=0;const claim=m=>{if(claimed)return;claimed=1;meta.credits+=credits*m;meta.reputation+=rep;save();result(1)};function result(done){rs.innerHTML=`<div class="result-card"><small>NIGHT SHIFT 2.0 · ${L('难度','TIER')} ${run.tier}</small><h2>${clear?L('灯还亮着','The Light Stays On'):L('卷帘门失守','The Shutter Falls')}</h2><p>${L('正确判断','Correct')} ${run.correct}/${run.order.length} · ${L('得分','Score')} ${score}</p><div class="result-grid"><span><b>+${credits}</b>${L('灯票','Tokens')}</span><span><b>+${rep}</b>${L('声望','Rep')}</span><span><b>${meta.streak}</b>${L('连胜','Streak')}</span></div><div class="reward-actions">${done?`<button class="primary" data-r="next">${L('再守一夜','Another Shift')}</button><button data-r="shop">${L('升级店铺','Upgrades')}</button>`:`<button class="primary" data-r="claim">${L('领取奖励','Claim')}</button>${window.LastLightPlatform?.canRewarded()?`<button data-r="double">${L('看广告 · 双倍','Watch Ad · Double')}</button>`:''}`}<button data-r="menu">${L('回到标题','Menu')}</button></div></div>`;rs.classList.add('show');rs.querySelector('[data-r=claim]')?.addEventListener('click',()=>claim(1));rs.querySelector('[data-r=double]')?.addEventListener('click',async()=>{(await window.LastLightPlatform.rewarded())?claim(2):claim(1)});rs.querySelector('[data-r=menu]').onclick=()=>{if(!claimed)claim(1);rs.classList.remove('show');menu.classList.add('show')};rs.querySelector('[data-r=next]')?.addEventListener('click',()=>{rs.classList.remove('show');start()});rs.querySelector('[data-r=shop]')?.addEventListener('click',shop)}result()}
function shop(){rs.classList.remove('show');sp.innerHTML=`<div class="shop-card"><button class="shop-close">${L('关闭','Close')}</button><small>PERMANENT UPGRADES</small><h2>${L('店铺升级','Store Upgrades')}</h2><div class="shop-credit">${L('灯票','Tokens')} <b>${meta.credits}</b></div><div class="shop-grid">${Object.entries(U).map(([id,d])=>{const lv=meta.upgrades[id]||0,c=cost(id),max=lv>=d[5];return`<button data-u="${id}" ${max?'disabled':''}><b>${d[en()?1:0]} ${lv}/${d[5]}</b><span>${d[en()?3:2]}</span><em>${max?L('已满级','MAX'):c+' '+L('灯票','tokens')}</em></button>`}).join('')}</div></div>`;sp.classList.add('show');sp.querySelector('.shop-close').onclick=()=>{sp.classList.remove('show');menu.classList.add('show')};sp.querySelectorAll('[data-u]').forEach(b=>b.onclick=()=>{const id=b.dataset.u,c=cost(id);if(meta.credits<c)return;meta.credits-=c;meta.upgrades[id]=(meta.upgrades[id]||0)+1;save();shop()})}
function menu2(){const t=tier(),done=meta.lastDaily===dk();lm.innerHTML=`<div class="liveops-wallet"><span>${L('灯票','Tokens')} <b>${meta.credits}</b></span><span>${L('声望','Rep')} <b>${meta.reputation}</b></span><span>${L('最高分','Best')} <b>${meta.bestScore}</b></span><span>${L('难度','Tier')} <b>${t}</b></span></div><button class="primary" data-m="n">${L('夜班守店 2.0','Night Shift 2.0')}<span>${L('30类来客 · 6–8回合','30 encounters · 6–8 rounds')}</span></button><button data-m="d">${L('今日契约','Daily Contract')}<span>${done?L('奖励已领取','Bonus claimed'):L('首次完成额外奖励','First clear bonus')}</span></button><button data-m="s">${L('永久升级','Permanent Upgrades')}<span>${L('七条成长路线','Seven upgrade paths')}</span></button>`;lm.querySelector('[data-m=n]').onclick=()=>start();lm.querySelector('[data-m=d]').onclick=()=>start(1);lm.querySelector('[data-m=s]').onclick=shop}menu2();
const br=typeof render==='function'?render:null;if(br)render=function(){norm();const x=br.apply(this,arguments);setTimeout(()=>{syncArt();syncCoach()},0);return x};new MutationObserver(()=>{syncArt();syncCoach()}).observe(sceneEl,{childList:1,subtree:1,attributes:1,attributeFilter:['class']});new MutationObserver(menu2).observe(document.documentElement,{attributes:1,attributeFilter:['lang','class']});syncArt();syncCoach();window.LastLightQA={run(){const missing=['scene','character','choices','restart'].filter(id=>!document.getElementById(id)),bad=typeof nodes==='undefined'?[]:Object.entries(nodes).flatMap(([id,n])=>(n.choices||[]).filter(c=>c[2]&&!nodes[c[2]]).map(c=>id+'>'+c[2]));return{missing,bad,encounters:E.length}}};setTimeout(()=>console.info('[Last Light QA]',window.LastLightQA.run()),1e3);
})();
