const $=id=>document.getElementById(id);let s={food:4,water:3,med:1,battery:1,trust:0,flags:{},node:'dawn',steps:1,found:{},talked:{},line:{},evidence:{}};let hasSave=false;try{let saved=JSON.parse(localStorage.getItem('lastLightStory')||'null');if(saved&&saved.node){s={...s,...saved};hasSave=s.steps>1||s.node!=='dawn'}}catch{}let crisisInterval=null,crisisLeft=0;
const investigations={
 dawn:[['ledger',19,72,'库存清单','清单被人改过：昨夜其实少了一盒药。'],['lock',72,43,'旧门锁','门锁没有撬痕，对方有仓库钥匙。']],
 clinic:[['footprint',38,70,'湿脚印','脚印通往便利店，鞋底沾着天台红漆。'],['window',72,46,'病房窗','玻璃内侧写着23:47，正是广播时间。']],
 diagnose:[['bottle',26,66,'空水瓶','瓶底有黑色沉淀，孩子更像饮水中毒。'],['mapmark',66,55,'地图','地图圈出了屋顶和地下通道。']],
 courtyard:[['tracks',47,72,'新脚印','一组去便利店，另一组爬上屋顶。'],['redlight',68,24,'红灯','红灯每七秒闪三次，是救援暗号。']],
 search:[['key',28,62,'旧钥匙','钥匙与便利店仓库门匹配。'],['siren',72,37,'巡逻灯','车辆没有官方编号。']],
 knock:[['shutter',50,54,'卷帘门','敲门节奏与广播底噪一样。'],['backdoor',20,70,'仓库异响','货架后有冷风，墙后还有空间。']],
 tunnel:[['recorder',34,58,'录音机','求救是循环录音，末尾混入真人坐标。'],['crates',72,64,'封存物资','封条属于已解散的应急部门。']],
 radio:[['radio',42,68,'无线电','频道上同时有撤离车和武装车队。'],['redlamp',72,24,'远处红灯','诊所的电只够再闪几次。']],ending:[]};
const dialogues={clinic:['林晓：你真的来了，先别靠近孩子。','林晓：广播不是我发的，但仓库钥匙被拿走了。','林晓：你愿意留下药吗？'],diagnose:['阿梨：她不是感染，你看这瓶水。','阿梨：红灯亮起时，地下门才会开。'],search:['老周：钥匙是别人塞进工具箱的。','老周：他说屋顶频率能带所有人离开。'],courtyard:['阿梨：屋顶的灯在给什么人发信号。'],radio:['阿梨：两辆车都在回应，只有一辆是真的。','阿梨：你决定坐标，我去叫其他人。'],ending:['阿梨：信号已经发出。']};
const evidenceNames={ledger:'改写清单',lock:'钥匙痕迹',footprint:'红漆脚印',window:'23:47',bottle:'污染水样',mapmark:'地下地图',tracks:'分岔脚印',redlight:'救援暗号',key:'仓库钥匙',siren:'假巡逻车',shutter:'敲门节奏',backdoor:'暗门冷风',recorder:'循环磁带',crates:'应急封条',radio:'双重频道',redlamp:'求救灯'};
const choiceRequirements={courtyard:{1:x=>x.battery>0?null:'需要电池'},radio:{0:x=>x.trust>=2?null:'需要信任 2',2:x=>(x.flags.tunnel||x.evidence.backdoor)?null:'尚未发现暗门'}};
const timedNodes={knock:18,radio:15};
const poseSets={clinic:['lin-guard','lin-point','lin-give'],diagnose:['ali-cautious','ali-map'],search:['lin-worry','ali-point'],radio:['ali-point','ali-lookback'],ending:['ali-lookback'],courtyard:['ali-cautious'],tunnel:[]};let poseTimer=null,poseIndex=0;
const sceneImg={backroom:'assets/story/backroom.webp',courtyard:'assets/story/courtyard.webp',store:'assets/fp/store-fp.webp',rooftop:'assets/story/rooftop.webp'};
const nodes={
 dawn:{scene:'backroom',title:'仓库 · 清晨',stamp:'07:10 / 暴雨',speaker:'旁白',text:'昨夜23点47分，屋顶电台收到一段只重复三次的求救：“青禾诊所……还有七个人。”天亮后，店里只剩一盒药，而发电机也快没油了。',choices:[['带药去诊所','药品 -1','clinic',x=>{x.med--;x.flags.tookMed=1}],['留下药，带电池调查信号','电池 -1','courtyard',x=>{x.battery--;x.flags.tookBattery=1}],['封门继续营业','保住物资','knock',x=>x.flags.stayed=1]]},
 clinic:{scene:'courtyard',title:'青禾诊所 · 黄昏',stamp:'17:35 / 封锁区',speaker:'林晓',text:'“广播不是我发的。昨晚有人闯进药房，留下了便利店仓库的旧钥匙。”她身后传来孩子压抑的咳嗽。远处巡逻灯正在接近。',choices:[['把药交给林晓','信任 +2','search',x=>{x.trust+=2;x.flags.savedChild=1}],['先检查孩子症状','获得线索','diagnose',x=>x.flags.cautious=1],['拿回药，追查旧钥匙','信任 -1','search',x=>{x.med++;x.trust--}]]},
 diagnose:{scene:'courtyard',title:'诊所病房 · 黄昏',stamp:'17:48 / 警报将至',speaker:'阿梨',text:'女孩的高烧来自污染水，不是感染。阿梨递给你一张地图：“屋顶红灯亮起时，地下仓库的门才会开。”',choices:[['留下净水和药','净水 -1，信任 +3','search',x=>{x.water--;x.trust+=3;x.flags.savedChild=1}],['只留下药，带走地图','获得仓库路线','search',x=>x.flags.hasMap=1]]},
 courtyard:{scene:'courtyard',title:'居民院 · 黄昏',stamp:'18:05 / 无人区',speaker:'旁白',text:'诊所门锁着。自行车棚下有新鲜脚印，一路通向便利店方向；屋顶红灯却在雨中规律闪烁，像某种暗号。',choices:[['循脚印返回便利店','可能遭遇闯入者','knock',x=>x.flags.followed=1],['立即登上屋顶电台','消耗电池获取信号','radio',x=>x.flags.signal=1],['撬开诊所侧门','罐头 -1','clinic',x=>x.food--]]},
 search:{scene:'courtyard',title:'废弃药房 · 入夜',stamp:'19:20 / 巡逻临近',speaker:'老周',text:'老周从柜台后站起来，手里握着你的仓库钥匙：“有人让我把钥匙带到屋顶。报酬是能让全街区撤离的频率。”外面传来车辆刹车声。',choices:[['相信老周，一起去屋顶','老周加入','radio',x=>{x.trust++;x.flags.zhou=1}],['拿回钥匙，躲进便利店','获得钥匙','knock',x=>x.flags.key=1],['让老周引开巡逻车','信任 -1','radio',x=>{x.trust--;x.flags.sacrifice=1}]]},
 knock:{scene:'store',title:'最后一盏灯 · 夜间',stamp:'21:40 / 卷帘门关闭',speaker:'门外的人',text:'卷帘门被敲了三长两短。灰帽商人喊道：“我知道广播是谁发的。开门，我用撤离名单换十瓶水。”与此同时，仓库门从里面响了一声。',choices:[['不开正门，检查仓库','发现隐藏通道','tunnel',x=>x.flags.tunnel=1],['开门让商人进来','净水 -2','radio',x=>{x.water-=2;x.flags.trader=1}],['熄灯，从后门去屋顶','电力保留','radio',x=>x.flags.darkExit=1]]},
 tunnel:{scene:'backroom',title:'仓库暗门 · 深夜',stamp:'22:15 / 地下震动',speaker:'阿梨',text:'货架后面的墙是空的。暗门里堆着政府封存的物资，以及一台仍在工作的录音机。求救广播正是从这里自动播放——它在引人来到这片街区。',choices:[['带走物资，关闭录音','罐头 +3，净水 +2','radio',x=>{x.food+=3;x.water+=2;x.flags.stoppedLoop=1}],['不碰物资，记录广播频率','获得真相线索','radio',x=>x.flags.truth=1]]},
 radio:{scene:'rooftop',title:'屋顶电台 · 午夜',stamp:'23:47 / 红灯亮起',speaker:'无线电',text:'耳机里终于出现真人声音：“这里是东线撤离车。只能停留六分钟。广播坐标已泄露，武装车队也在赶来。”楼下，诊所和便利店同时亮起求救灯。',choices:[['广播诊所坐标，先救病人','需要足够信任','ending',x=>x.flags.choseClinic=1],['广播便利店坐标，带走物资','保住财富','ending',x=>x.flags.choseStore=1],['保持静默，带所有人走地下通道','需要发现暗门','ending',x=>x.flags.choseTunnel=1]]},
 ending:{scene:'rooftop',title:'第一章终章 · 失联者',stamp:'00:03 / 选择已发送',speaker:'旁白',text:s=>{let f=s.flags;if(f.choseTunnel&&f.tunnel)return'你没有回答无线电。阿梨带着众人穿过地下仓库，红灯在身后熄灭。撤离车扑了个空，但所有人都活着。';if(f.choseClinic&&s.trust>=2)return'撤离车先抵达诊所。林晓抱着退烧的孩子上车，老周则回头守住便利店。你失去了大半物资，却得到一个愿意保护你的街区。';if(f.choseStore)return'撤离车停在便利店门前。你带走了物资和钥匙，却看见诊所的灯在后视镜中熄灭。那段广播从此再也没有响起。';return'坐标发出后，两个方向同时亮起车灯。你的准备不足以救下所有人。第一章结束，但这个选择会跟随你进入下一章。'},choices:[['重新体验第一章','查看其他分支','dawn',x=>Object.assign(x,{food:4,water:3,med:1,battery:1,trust:0,flags:{},steps:0,found:{},talked:{},line:{},evidence:{}})]]}
};
// Forward-compatible save placeholder; later chapter layers replace this before play continues.
nodes.ambush={scene:'store',title:'便利店反制 · 暴雨夜',stamp:'22:03 / 恢复现场',speaker:'旁白',text:'正在恢复反制现场……',choices:[]};
nodes.alley={scene:'courtyard',title:'积水后巷 · 雨幕',stamp:'08:05 / 路线中断',speaker:'旁白',text:'正在恢复后巷现场……',choices:[]};
nodes.garage={scene:'backroom',title:'后仓机修间 · 封锁线',stamp:'20:10 / 闸门故障',speaker:'旁白',text:'正在恢复车库现场……',choices:[]};
nodes.c2_dawn={scene:'store',title:'第二夜 · 黑雨',stamp:'06:40 / 水源警报',speaker:'旁白',text:'正在恢复第二章……',choices:[]};
nodes.c2_roof={scene:'rooftop',title:'屋顶集水区',stamp:'07:25 / 黑色沉淀',speaker:'旁白',text:'正在恢复第二章……',choices:[]};
nodes.c2_market={scene:'courtyard',title:'居民院配水点',stamp:'11:10 / 人群失控',speaker:'旁白',text:'正在恢复第二章……',choices:[]};
nodes.c2_suyan={scene:'courtyard',title:'雨棚下的交易',stamp:'15:40 / 定位信号',speaker:'旁白',text:'正在恢复第二章……',choices:[]};
nodes.c2_pump={scene:'backroom',title:'地下泵站',stamp:'19:30 / 水位上涨',speaker:'旁白',text:'正在恢复第二章……',choices:[]};
nodes.c2_choice={scene:'rooftop',title:'示踪发射塔',stamp:'23:12 / 白塔接近',speaker:'旁白',text:'正在恢复第二章……',choices:[]};
nodes.c2_end={scene:'rooftop',title:'第二章终章',stamp:'23:47 / 信号已发出',speaker:'旁白',text:'正在恢复第二章结局……',choices:[]};
function showPose(index=0){let poses=poseSets[s.node]||[],el=$('character');if(!poses.length){el.classList.remove('show');el.style.backgroundImage='none';return}let p=poses[index%poses.length];el.style.backgroundImage=`url('assets/story/characters/${p}.webp')`;el.classList.remove('swap');el.classList.add('show')}
function setCharacter(){clearInterval(poseTimer);poseIndex=0;showPose(0)}
function say(text){let e=$('speech');e.textContent=text;e.classList.add('show');clearTimeout(s._speechTimer);s._speechTimer=setTimeout(()=>e.classList.remove('show'),4200)}
function renderInteractions(){let list=investigations[s.node]||[],root=$('hotspots');root.innerHTML='';let found=s.found[s.node]||[];list.forEach(([id,x,y,label,text])=>{let b=document.createElement('button');b.className='hotspot'+(found.includes(id)?' found':'');b.dataset.label=label;b.style.left=x+'%';b.style.top=y+'%';b.onclick=()=>{if(!found.includes(id)){found.push(id);s.found[s.node]=found;s.evidence[id]=evidenceNames[id]||label;renderEvidence()}b.classList.add('found');say(text);updateLocks()};root.appendChild(b)});$('character').onclick=()=>{let lines=dialogues[s.node]||[];if(!lines.length)return;let i=s.line[s.node]||0;s.line[s.node]=i+1;s.talked[s.node]=true;showPose(i);say(lines[i%lines.length]);updateLocks()};updateLocks()}
function ready(){let list=investigations[s.node]||[],found=(s.found[s.node]||[]).length,needsTalk=(dialogues[s.node]||[]).length>0;if(s.node==='ending')return true;return found>=Math.min(1,list.length)&&(!needsTalk||s.talked[s.node])}
function updateLocks(){let ok=ready(),count=(s.found[s.node]||[]).length+(s.talked[s.node]?1:0),total=Math.min(1,(investigations[s.node]||[]).length)+((dialogues[s.node]||[]).length?1:0);$('clueCount').textContent=count+' / '+total;$('clueList').textContent=ok?'线索足够，可以作出决定':((dialogues[s.node]||[]).length&&!s.talked[s.node]?'先点击人物交谈':'点击场景中的发光位置');$('choices').dataset.hint=ok?'你准备怎么做？':'调查场景后解锁选择';$('choices').querySelectorAll('button').forEach(b=>b.classList.toggle('locked',!ok))}
function renderEvidence(){let root=$('evidenceList'),vals=Object.values(s.evidence||{}).slice(-6);root.innerHTML=vals.length?vals.map(x=>`<span class="evidence-chip">${x}</span>`).join(''):'<span class="evidence-empty">尚无证物</span>'}
function startCrisis(){clearInterval(crisisInterval);let total=timedNodes[s.node],bar=$('crisisTimer');if(!total){bar.classList.remove('show');return}crisisLeft=total;bar.classList.add('show');bar.dataset.label='危机倒计时 '+crisisLeft+'s';$('crisisBar').style.width='100%';crisisInterval=setInterval(()=>{crisisLeft--;bar.dataset.label='危机倒计时 '+crisisLeft+'s';$('crisisBar').style.width=(crisisLeft/total*100)+'%';if(crisisLeft<=0){clearInterval(crisisInterval);if(s.node==='knock'){s.trust--;go('radio',x=>x.flags.darkExit=1)}else if(s.node==='radio'){go('ending',x=>x.flags.choseStore=1)}}},1000)}
function render(){let n=nodes[s.node];$('sceneTitle').textContent=n.title;$('speaker').textContent=n.speaker;$('text').textContent=typeof n.text==='function'?n.text(s):n.text;$('scene').style.backgroundImage=`url('${sceneImg[n.scene]}')`;$('stamp').textContent=n.stamp;['food','water','med','battery','trust'].forEach(k=>$(k).textContent=s[k]);$('progress').textContent=Math.min(s.steps,8)+' / 8';setCharacter();$('speech').classList.remove('show');$('choices').innerHTML='';n.choices.forEach(([label,cost,next,effect],choiceIndex)=>{let b=document.createElement('button');let req=choiceRequirements[s.node]?.[choiceIndex]?.(s);b.innerHTML=`${label}<small>${req||cost}</small>`;if(req)b.classList.add('unavailable');b.onclick=()=>{if(req){say(req+'\uFF0C\u5148\u5728\u573A\u666F\u4E2D\u5BFB\u627E\u529E\u6CD5\u3002');return}if(b.classList.contains('locked')){say('\u8fd8\u7f3a\u5c11\u5173\u952e\u4fe1\u606f\u3002\u70b9\u51fb\u4eba\u7269\u548c\u53d1\u5149\u4f4d\u7f6e\u3002');return}go(next,effect)};$('choices').appendChild(b)});renderInteractions();renderEvidence();startCrisis();if(s.node==='ending'){let f=s.flags,id=f.choseTunnel&&f.tunnel?'tunnel':f.choseClinic&&s.trust>=2?'clinic':f.choseStore?'store':'lost';localStorage.setItem('lastLightEnding',id);$('chapterComplete').innerHTML='<b>\u7b2c\u4e00\u7ae0\u5b8c\u6210</b>\u7ed3\u5c40\u5df2\u6536\u5f55\uff0c\u4f60\u53ef\u4ee5\u91cd\u65b0\u9009\u62e9\u5176\u4ed6\u8def\u7ebf\u3002';$('chapterComplete').classList.add('show')}else $('chapterComplete').classList.remove('show');localStorage.setItem('lastLightStory',JSON.stringify(s))}
function go(next,effect){clearInterval(crisisInterval);$('scene').classList.add('fade');setTimeout(()=>{effect&&effect(s);s.node=next;s.steps++;render();$('scene').classList.remove('fade')},300)}$('scene').appendChild(document.querySelector('header'));$('scene').appendChild(document.querySelector('.resources'));
let menu=document.createElement('div');menu.id='startMenu';menu.className='start-menu show';menu.innerHTML='<div class="start-card"><small>LAST LIGHT</small><h2>\u6700\u540e\u4e00\u76cf\u706f</h2><p>\u4e00\u5bb6\u4fbf\u5229\u5e97\uff0c\u4e03\u4e2a\u96e8\u591c\uff0c\u4ee5\u53ca\u4f60\u65e0\u6cd5\u540c\u65f6\u6551\u4e0b\u7684\u4eba\u3002</p><div class="menu-actions"><button id="continueGame" class="primary">\u7ee7\u7eed\u6e38\u620f<span>\u81ea\u52a8\u5b58\u6863</span></button><button id="newGame">\u65b0\u7684\u6545\u4e8b<span>\u91cd\u7f6e\u8fdb\u5ea6</span></button><button id="closeMenu">\u8fd4\u56de\u573a\u666f</button></div><p class="save-note">\u6e38\u620f\u4f1a\u5728\u6bcf\u6b21\u51b3\u5b9a\u540e\u81ea\u52a8\u4fdd\u5b58</p></div>';$('scene').appendChild(menu);let complete=document.createElement('div');complete.id='chapterComplete';complete.className='chapter-complete';$('scene').appendChild(complete);
let ev=document.createElement('aside');ev.className='evidence-tray';ev.innerHTML='<h3>\u8bc1\u7269\u5305</h3><div id="evidenceList" class="evidence-list"></div>';$('scene').appendChild(ev);let timer=document.createElement('div');timer.id='crisisTimer';timer.className='crisis-timer';timer.innerHTML='<i id="crisisBar"></i>';$('scene').appendChild(timer);$('scene').appendChild(document.querySelector('.cluebar'));$('scene').appendChild(document.querySelector('.narrative'));
function resetStory(){s={food:4,water:3,med:1,battery:1,trust:0,flags:{},node:'dawn',steps:1,found:{},talked:{},line:{},evidence:{}};localStorage.removeItem('lastLightStory');render();menu.classList.remove('show')}
$('restart').textContent='\u83dc\u5355';$('restart').onclick=()=>menu.classList.add('show');$('continueGame').style.display=hasSave?'block':'none';$('continueGame').onclick=()=>menu.classList.remove('show');$('closeMenu').onclick=()=>menu.classList.remove('show');$('newGame').onclick=resetStory;render();





