/* Runtime localization for the market build. English is the CrazyGames default; Chinese remains selectable. */
(() => {
  const savedLanguage = localStorage.getItem('lastLightLanguage');
  const queryLanguage = new URLSearchParams(location.search).get('lang');
  const language = queryLanguage === 'zh' || queryLanguage === 'en' ? queryLanguage : (savedLanguage === 'zh' ? 'zh' : 'en');
  const english = language === 'en';
  document.documentElement.lang = english ? 'en' : 'zh-CN';
  document.documentElement.classList.toggle('lang-en', english);
  document.title = english ? 'Last Light Mart: The Missing Signal' : '最后一盏灯：失联者';

  const exact = {
    '菜单':'Menu','关闭':'Close','返回标题':'Back to Title','回到标题':'Back to Title','继续游戏':'Continue','自动存档':'Autosave','新的故事':'New Story','重置进度':'Reset Progress','返回场景':'Return to Scene',
    '游戏会在每次决定后自动保存':'Your progress is saved after every decision.','最后一盏灯':'Last Light Mart','一家便利店，七个雨夜，以及你无法同时救下的人。':'One convenience store. Seven nights of rain. Not everyone can be saved.',
    '罐头':'Food','净水':'Water','药品':'Medicine','电池':'Battery','信任':'Trust','现场调查':'INVESTIGATION','点击发光位置寻找线索':'Tap glowing areas to search for clues.',
    '线索足够，可以作出决定':'Evidence complete. Make your decision.','先点击人物交谈':'Talk to the person first.','点击场景中的发光位置':'Tap a glowing point in the scene.','你准备怎么做？':'What will you do?','调查场景后解锁选择':'Investigate the scene to unlock choices.',
    '尚无证物':'No evidence yet','证物包':'EVIDENCE','线索':'Clue','选择回响':'CONSEQUENCE','整理证据 · 作出推断':'Review Evidence · Deduce','跳过镜头':'Skip Scene','自由调查':'FREE INVESTIGATION','有人在等你回应':'Someone is waiting for your response.','别放过画面里的异常':'Look for anything out of place.',
    '先点击画面中的人物，让她把话说完。':'Talk to the person in the scene first.','点击画面中微微发光的位置，靠近查看。':'Tap the faintly glowing areas for a closer look.','关键细节已经到手。':'You have the key details.',
    '推理板 / 两处证物只能支持一个结论':'DEDUCTION BOARD / The evidence supports only one conclusion','拖到人物或发光物体上':'Drag onto a person or glowing object','已拿出':'Selected','点击画面中的人或物':'Tap a person or object in the scene.',
    '设置 / 教学':'Settings / Tutorial','结局档案':'Ending Archive','游戏设置':'Game Settings','环境声音':'Ambient Sound','触感反馈':'Haptic Feedback','操作教学':'Tutorial','重新播放':'Replay','开启':'On','关闭声音':'Mute Sound','打开声音':'Enable Sound',
    '操作教学':'Tutorial','教学完成':'Tutorial Complete','以后可在设置中重新查看':'Replay it later from Settings.','跳过教学':'Skip Tutorial','自动存档':'Autosave',
    '第一季 · 七个雨夜':'SEASON ONE · SEVEN NIGHTS','当前开放：第一章、第二章':'Available now: Chapters One and Two','第二章：雨水有毒':'Chapter Two: Poison Rain','第二章：完成第一章后解锁':'Chapter Two: Complete Chapter One to Unlock',
    '第一章 · 失联者':'CHAPTER ONE · MISSING SIGNAL','第二章 · 雨水有毒':'CHAPTER TWO · POISON RAIN','目标：查明昨夜广播的来源':'OBJECTIVE: Trace last night’s broadcast','目标：查明黑雨为什么标记幸存者':'OBJECTIVE: Learn why the black rain marks survivors',
    '途中结果':'ROUTE RESULT','你看穿了路况':'You Read the Route','你抢到了时间':'You Gained Time','继续前进':'Continue','路线判断':'ROUTE DECISION','现在决定怎么通过，不同走法会被后面的角色记住。':'Choose how to cross. Later characters will remember your approach.','第二个现场决定':'SECOND FIELD DECISION',
    '途中事件':'ROUTE EVENT','停下观察动静':'Stop and observe','沿遮蔽物慢行':'Move behind cover','冒雨抢时间':'Rush through the rain','安全路线在雨里不断变化。你必须先看清遮蔽物、积水和远处灯光。':'The safe route keeps changing in the rain. Read the cover, water and distant lights before moving.','你用更慢的路线避开了暴露位置。':'You take the slower route and avoid exposure.','你抢到时间，也让远处的人看见了移动的灯光。':'You gain time, but distant eyes notice your moving light.',
    '保持隐蔽':'Stay Hidden','抢到先机':'Seize Initiative','信任上升':'Trust Increased','信任下降':'Trust Decreased','之后的人会记得':'People will remember this.','有效操作':'Effective Action','证据链':'Evidence Chain','推断成立':'DEDUCTION CONFIRMED','反制能量':'Counter Energy','危机倒计时':'CRISIS',
    '第一章完成':'CHAPTER ONE COMPLETE','结局已收录，你可以重新选择其他路线。':'Ending archived. Replay to discover another route.','最终信任':'Final Trust','发现线索':'Clues Found','关键决定':'Key Decisions','结局收集':'Endings Collected','换一条路':'Choose Another Route',
    '第二章结局':'Chapter Two Endings','第一季进度':'Season One Progress','重玩第二章':'Replay Chapter Two','进入第二章':'Enter Chapter Two','关闭密钥':'Shutdown Keys','累计线索':'Total Clues','街区信任':'District Trust',
    '章节结算':'CHAPTER REWARD','永久升级已开放':'Permanent upgrades unlocked','第一季进度继续保留':'Season progress retained',
    '夜班守店':'Night Shift','可重复挑战 · 赚取灯票':'Repeatable run · Earn Light Tokens','今日契约':'Daily Contract','每日固定事件与额外奖励':'Fixed daily encounters and bonus rewards','永久升级':'Permanent Upgrades','强化背包、滤芯、短波与门锁':'Improve your pack, filter, radio and shutter lock',
    '灯票':'Light Tokens','声望':'Reputation','最高分':'Best Score','夜班':'Shifts','今日额外奖励已领取 · 仍可练习':'Daily bonus claimed · Practice remains available','每日固定事件 · 首次完成 +25灯票':'Fixed daily run · First clear +25 Light Tokens',
    '最后一盏灯 · 夜班守店':'Last Light Mart · Night Shift','风险未知':'Risk Unknown','风险较低':'LOW RISK','风险很高':'HIGH RISK','调查身份':'Investigate','接受交易':'Accept Trade','拒绝开门':'Keep Door Closed','调查后才能看到关键细节':'Investigate to reveal the key details.','已经调查':'Investigated',
    '判断正确':'Correct Call','判断失误':'Wrong Call','店铺':'Shutter','调查':'Checks','得分':'Score','回合':'Visitor','灯还亮着':'The Light Stays On','卷帘门失守':'The Shutter Fell','领取奖励':'Claim Reward','看广告 · 双倍灯票':'Watch Ad · Double Tokens','正在请求广告…':'Requesting Ad…','暂无广告 · 正常领取':'No Ad Available · Claim Normally','再守一夜':'Guard Another Night','升级店铺':'Upgrade Store',
    '店铺升级':'Store Upgrades','夜班赚取灯票，永久强化下一次守店。所有奖励都能通过正常游玩获得。':'Earn Light Tokens during shifts and permanently strengthen future runs. Every reward is obtainable through normal play.','已满级':'MAX LEVEL','广告播放中':'ADVERTISEMENT',
    '先听人物说完':'Hear Them Out','点击画面中的人物。对话会提供调查方向，也会影响你之后能做出的决定。':'Tap the person in the scene. Dialogue reveals investigation leads and affects later decisions.','调查异常位置':'Search Suspicious Areas','点击画面里带金色光圈的位置，靠近查看证物。':'Tap the gold-marked areas to inspect evidence.','亲手检查证物':'Inspect It Yourself','先完成检查动作，再拖动出现的滑块，把细节看清楚。':'Complete the inspection action, then move the slider to reveal the detail.','整理完整证据':'Complete the Evidence','继续调查另一处异常。证物齐全后，点击“整理证据 · 作出推断”。':'Investigate the second anomaly, then open Review Evidence to make a deduction.','根据推断行动':'Act on Your Deduction','选择最符合证据的结论。推断完成后，再从底部选择你的行动路线。':'Choose the conclusion best supported by the evidence, then select your route.',
    '无人生还名单':'Ghost Manifest','灯灭之后':'After the Lights Go Out','街区仍在':'The District Survives','满载而去':'Leave Fully Stocked','错误坐标':'Wrong Coordinates','未解锁':'Locked','继续调查，寻找另一种可能。':'Keep investigating to find another outcome.','已收集':'Collected',
    '正在加载雨夜现场':'Loading the Rain-Swept City','准备人物、证物与下一段路线…':'Preparing characters, evidence and the next route…'
  };

  const regex = [
    [/^危机倒计时\s*(\d+)s$/,'CRISIS $1s'],
    [/^反制能量\s*(\d+)%$/,'COUNTER ENERGY $1%'],
    [/^调查身份 · (\d+)次$/,'Investigate · $1 left'],
    [/^回合\s*(\d+)\/(\d+)$/,'Visitor $1/$2'],
    [/^正确判断\s*(\d+)\/(\d+)\s*·\s*店铺耐久\s*(\d+)\s*·\s*本局得分\s*(\d+)$/,'Correct calls $1/$2 · Shutter $3 · Run score $4'],
    [/^灯票\s*\+(\d+)$/,'Light Tokens +$1'],
    [/^章节结算\s*·\s*灯票\s*\+(\d+)\s*·\s*(.*)$/,'CHAPTER REWARD · Light Tokens +$1 · $2'],
    [/^(\d+)\s*灯票$/,'$1 Light Tokens'],
    [/^谨慎路线\s*(\d+)$/,'Careful routes $1'],
    [/^强攻路线\s*(\d+)$/,'Bold routes $1'],
    [/^信任\s*\+(\d+)$/,'Trust +$1'],
    [/^电池\s*-(\d+)$/,'Battery -$1'],
    [/^净水\s*-(\d+)$/,'Water -$1'],
    [/^药品\s*-(\d+)$/,'Medicine -$1']
  ];

  function translateText(value) {
    if (!english || typeof value !== 'string') return value;
    const leading = value.match(/^\s*/)?.[0] || '';
    const trailing = value.match(/\s*$/)?.[0] || '';
    const core = value.trim();
    if (!core) return value;
    if (exact[core]) return leading + exact[core] + trailing;
    for (const [pattern,replacement] of regex) if (pattern.test(core)) return leading + core.replace(pattern,replacement) + trailing;
    let next = core;
    const prefixes = [['判断正确：','Correct Call: '],['判断失误：','Wrong Call: '],['获得：','Gained: '],['需要','Requires '],['没有可用','No ']];
    prefixes.forEach(([from,to])=>{if(next.startsWith(from))next=to+next.slice(from.length)});
    return leading + next + trailing;
  }

  function translateDom(root=document.body) {
    if (!english || !root) return;
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
    const nodesToTranslate=[];let node;
    while((node=walker.nextNode())){if(!node.parentElement?.closest('script,style'))nodesToTranslate.push(node)}
    nodesToTranslate.forEach(textNode=>{const next=translateText(textNode.nodeValue);if(next!==textNode.nodeValue)textNode.nodeValue=next});
    root.querySelectorAll?.('[title],[aria-label],[data-label]').forEach(el=>{
      ['title','aria-label','data-label'].forEach(attr=>{if(el.hasAttribute(attr)){const old=el.getAttribute(attr),next=translateText(old);if(next!==old)el.setAttribute(attr,next)}})
    });
  }

  function replaceObjectStrings(value) {
    if (!english || value==null) return value;
    if (typeof value === 'string') return translateText(value).trim();
    if (Array.isArray(value)) { value.forEach((entry,index)=>{if(typeof entry==='string')value[index]=translateText(entry).trim();else replaceObjectStrings(entry)}); return value; }
    if (typeof value === 'object') Object.values(value).forEach(replaceObjectStrings);
    return value;
  }

  function setChoices(nodeId,choices){const list=nodes[nodeId]?.choices||[];choices.forEach((choice,index)=>{if(list[index]){list[index][0]=choice[0];list[index][1]=choice[1]}})}
  function setNode(nodeId,data){if(!nodes[nodeId])return;Object.assign(nodes[nodeId],data);if(data.choices)setChoices(nodeId,data.choices)}

  function applyEnglishContent(){
    Object.assign(itemLabels,{med:'Medicine',water:'Water',battery:'Battery',ledger:'Altered Inventory',lock:'Key Marks',footprint:'Red-Paint Footprint',window:'23:47',bottle:'Contaminated Water',mapmark:'Utility Map',tracks:'Split Footprints',redlight:'Rescue Signal',key:'Warehouse Key',siren:'Fake Patrol Car',shutter:'Knock Pattern',backdoor:'Hidden-Door Draft',recorder:'Looping Tape',crates:'Emergency Seal',radio:'Two Frequencies',redlamp:'Rescue Lamp',wire:'Tripwire',cable:'Winch Cable',rainbarrel:'Black-Rain Sample',tracker:'White Tower Tracker',sistercode:"Sister's Verification Code"});
    Object.assign(evidenceNames,{ledger:'Altered Inventory',lock:'Fresh Key Marks',footprint:'Red-Paint Footprint',window:'23:47',bottle:'Contaminated Water Sample',mapmark:'Underground Utility Map',tracks:'Split Footprints',redlight:'Rescue Challenge Signal',key:'Warehouse Key',siren:'Unmarked Patrol Car',shutter:'Knock Pattern',backdoor:'Hidden Passage Draft',recorder:'Looping Distress Tape',crates:'Emergency Department Seal',radio:'Overlapping Frequencies',redlamp:'Rescue Lamp',wire:'Flooded Tripwire',cleanboot:'Dry Foothold',cable:'Cut Winch Cable',badge:'Fire-Rescue Badge',glove:'Two-Finger Glove',forgery:'Forged Evacuation List',rainbarrel:'Black-Rain Sediment',flyer:'White Tower Flyer',filter:'Slashed Filter',bluepowder:'Blue Tracer Powder',rationmark:'Altered Ration Line',sickbird:'Poisoned Swift',tracker:'White Tower Tracker',tripwire:'Submerged Tripwire',valve:'Pump Valve',seal:'L-17 Seal',antenna:'Tracking Antenna',sistercode:"Sister's Verification Code",towerRoster:'Locked-Floor Roster',executiveCard:'White Tower Executive Keycard'});
    Object.assign(relationLabels,{lin:'Lin Xiao',ali:'Ali',zhou:'Old Zhou',suyan:'Su Yan',chengye:'Cheng Ye'});

    investigations.dawn=[['ledger',64,82,'Inventory Sheet','A half fingerprint stains only the missing-medicine row. The water trail runs from the entrance toward the counter.'],['lock',35,84,'Old Warehouse Key','Fresh red paint is caught between the teeth. The key lacks the oily wear of long storage.']];
    investigations.alley=[['wire',70,79,'Flooded Tripwire','A transparent line ends at three empty cans aimed toward the street. It is too weak to stop a person, but perfect for making noise.'],['cleanboot',35,74,'Dry Foothold','Only one brick remains dry. Su Yan keeps her toe on its edge, and her reaching hand guides you directly across the wire.']];
    investigations.clinic=[['footprint',38,70,'Wet Footprints','The same shoes traveled between the clinic and the store. Wet red paint is trapped in the heel.'],['window',72,46,'Ward Window','“23:47” was written from inside the room, facing outward.']];
    investigations.diagnose=[['bottle',54,57,'Black Water Sample','The particles cling to the metal cap. This is not ordinary mud.'],['mapmark',79,29,'Maintenance Route Map','A red line links the old pharmacy, rear workshop and rooftop antenna.']];
    investigations.search=[['key',28,62,'Old Key','It opens the store warehouse. Its teeth carry the same red paint as the antenna base.'],['siren',72,37,'Patrol Light','The light sweeps every seven seconds. The vehicle has no number and rooftop sealant on its tires.']];
    investigations.garage=[['cable',12,66,'Cut Cable','The winch cable was deliberately severed. A battery can bridge it temporarily.'],['badge',78,42,'Old Badge','A fire-rescue badge lies under the shutter. The number belongs to Cheng Ye.']];
    investigations.ambush=[['glove',12,68,'Damaged Glove','Two fingers on the left hand are sewn shut, matching Old Zhou’s description.'],['forgery',78,42,'Evacuation List','The stamp belongs to an emergency agency dissolved before the disaster.']];
    investigations.c2_dawn=[['rainbarrel',12,68,'Rain Barrel','The black sediment is magnetic, not mud.'],['flyer',78,42,'Soaked Flyer','The back reads: “Settlement Tracking and Recovery.”']];
    investigations.c2_roof=[['filter',12,66,'Slashed Filter','The filter was cut from the inside, allowing tracer powder into the building water.'],['bluepowder',78,38,'Blue Powder','It glows in rain and can be detected from the air.']];
    investigations.c2_market=[['rationmark',12,70,'Bucket Mark','Someone raised the ration line to manufacture conflict.'],['sickbird',78,43,'Dead Swift','Its tag carries a White Tower environmental-monitoring number.']];
    investigations.c2_suyan=[['tracker',23,70,'Hidden Remote','A remote against Su Yan’s leg is transmitting your position.'],['tripwire',55,78,'Submerged Wire','The line crosses the water and connects to a shock canister under the truck.']];
    investigations.c2_pump=[['valve',12,67,'Pump Valve','The locked valve has a battery bypass port.'],['seal',78,42,'L-17 Seal','The pump seal matches the convenience-store node number.']];
    investigations.c2_choice=[['antenna',12,66,'Tracking Antenna','The antenna is reporting the district population to White Tower.'],['sistercode',78,38,'Verification Code','The corroded panel carries the seven-digit format your sister always used.']];

    dialogues.dawn=['Su Yan: Twenty-eight, former combat medic. She keeps both hands visible. “Check me for weapons before you decide whether to trust me.”','Su Yan: She slides the medical bag across the counter. “One box of medicine is missing, right? Someone came before me.”','Su Yan: “That ambulance outside is not mine. Stay close—but do not copy every step I take.”'];
    dialogues.alley=['Su Yan: She pins the only dry foothold with one boot. “Come here, or keep watching the wire. You have five seconds.”','Su Yan: She catches your wrist while nudging your shoe away from the tripwire. “Good. At least you know danger is not always the person in front of you.”','Su Yan: “You did not follow the path I designed. The real clinic entrance is only for people who stay alert.”'];
    dialogues.clinic=['Lin Xiao: “You actually came. Do not approach the child yet.”','Lin Xiao: “I did not send the broadcast, but someone took the warehouse key.”','Lin Xiao: “Will you leave the medicine?”'];
    dialogues.diagnose=['Ali: “I am twenty-four. I repair radios. Something in this water answers electromagnetic pulses.”','Ali: “They are not trying to kill everyone. They are counting occupied buildings from the air.”'];
    dialogues.search=['Old Zhou: “Someone planted the key in my toolbox.”','Old Zhou: “He said the rooftop frequency could evacuate the whole district.”'];
    dialogues.garage=['Cheng Ye: “Cheng Ye, thirty-two, former fire rescue. I can hold this shutter for ten seconds.”','Cheng Ye: “Do not play hero. You wire the power. I hold the weight. Everyone crosses.”'];
    dialogues.ambush=['Gray Hat: “You think catching me means you won? The convoy already has the coordinates.”','Gray Hat: “The real East Line asks whether the light is still on. The fake convoy only asks for a headcount.”'];
    dialogues.radio=['Ali: “Both convoys are answering. Only one is real.”','Ali: “Choose the coordinates. I will gather the others.”'];
    dialogues.c2_dawn=['Lin Xiao: “The child did not relapse. The rainwater caused this.”','Lin Xiao: “The sediment marks buildings. It does not kill immediately.”'];
    dialogues.c2_roof=['Cheng Ye: “The filter did not fail. Someone cut it from the inside.”','Cheng Ye: “Give me three minutes and I can remove the collector.”'];
    dialogues.c2_market=['Lin Xiao: “If we hide the truth any longer, people will fight over the clean water first.”'];
    dialogues.c2_suyan=['Su Yan: “Pull me up. The water is rising. Look down at the wire and we both run out of time.”','Su Yan: “You always know I am lying, and you still reach out.”','Su Yan: “Fine. You ignored what I wanted you to see. White Tower ordered me to bring this tracker close to you.”'];
    dialogues.c2_pump=['Ali: “L-17 is not the store number. It is a lighthouse node.”','Ali: “Your sister’s name is on the final maintenance record.”'];
    dialogues.c2_choice=['Ali: “Your sister’s code can hijack the antenna, but only once.”','Ali: “Destroying it is safest. Taking control might save more people.”'];

    setNode('dawn',{title:'Last Light Mart · Rain at Dawn',stamp:'07:10 / Shutter Half Open',speaker:'Su Yan',text:'The shutter is only waist-high when Su Yan slips in from the storm. She drops a red medical bag beside her feet and asks for help, but her eyes check the medicine cabinet, rear door and radio first. The dial still reads 23:47, and exactly one box of medicine is missing.',choices:[['Take the medicine and follow her to the ambulance','Keep the medicine with you'],['Make her walk ahead while you check the footprints','Chance to expose the lie'],['Hold the medical bag as collateral and flank through the side door','Take control of the pace']]});
    setNode('alley',{title:'Flooded Back Alley · Rain Curtain',stamp:'08:05 / Route Blocked',speaker:'Su Yan',text:'The ambulance doors stand open under a warm warning light. Su Yan reaches toward you while deliberately blocking the clearest view of the water. Look away from the ground and you will miss the transparent wire tied to empty cans. An unmarked patrol vehicle is already turning into the street.',choices:[['Support her and take the shortcut','She appears to need help'],['Pretend to fall for it, then cut the wire','Counter successful · Battery +1'],['Make her cross first and lead the way','Force her through her own trap']]});
    setNode('clinic',{title:'Qinghe Clinic · Sealed Lobby',stamp:'08:40 / First Patrol Sweep',speaker:'Lin Xiao',text:'Lin Xiao opens the side door only a crack. Someone stole fever medicine last night and left your warehouse key beside a hospital bed. The patients drank from the same rainwater supply. An unmarked patrol is checking every lit building on the street.',choices:[['Give the medicine to Lin Xiao','Medicine -1 · Trust +2'],['Examine the child first','Gain evidence'],['Keep the medicine and trace the old key','Lin Xiao relationship -1']]});
    setNode('diagnose',{title:'Qinghe Clinic · Water Diagnosis',stamp:'09:05 / Black Sediment Appears',speaker:'Ali',text:'Ali raises the black sediment toward the lamp. This is poisoning, not infection. Behind her, Lin Xiao stabilizes the child while a wall map links the rooftop antenna, old pharmacy and underground service route.',choices:[['Leave clean water and medicine','Water -1 · Medicine -1'],['Leave only the medicine and take the map','Gain the warehouse route']]});
    setNode('search',{title:'Abandoned Pharmacy · Unmarked Patrol',stamp:'11:20 / Blockade Closing',speaker:'Old Zhou',text:'Old Zhou is holding your warehouse key. A gray-hatted trader paid him with an “evacuation frequency” to carry the key upstairs. The unmarked patrol has sealed the main road; the connected rear workshop is the only exit.',choices:[['Trust Old Zhou and head for the roof together','Old Zhou joins'],['Take the key and hide in the store','Gain the key'],['Make Old Zhou draw the patrol away','Trust -1']]});
    setNode('garage',{title:'Rear Workshop · Blockade',stamp:'13:10 / Shutter Falling',speaker:'Cheng Ye',text:'The shutter crashes down until a bandaged hand stops it. Cheng Ye braces under the weight. “I hold it. You reconnect the power. Move.”',choices:[['Lift the shutter with him','Cheng Ye joins'],['Restart the winch and move everyone through','Repair it for a full evacuation'],['Leave him behind while you escort Old Zhou out','Trust -1']]});
    setNode('knock',{title:'Last Light Mart · Night',stamp:'20:40 / Seven Hours Holding Out',speaker:'Voice Outside',text:x=>x.momentum>=25?'You spend the afternoon moving survivors, medicine and evidence back to the store. Three long knocks and two short finally strike the shutter. Gray Hat is still selling an evacuation list, but now your evidence can become a trap.':'You barely make it back before dark. Gray Hat offers an evacuation list for ten bottles of water. The same knock answers from inside the warehouse, proving there is another route.',choices:[['Keep the front closed and inspect the warehouse','Discover a hidden passage'],['Open the door for the trader','Water -2'],['Kill the lights and leave through the rear','Preserve power'],['Open deliberately, cut the power and trap Gray Hat','Spend 25 Counter Energy']]});
    setNode('ambush',{title:'Store Counterattack · Storm Night',stamp:'22:03 / Hunter in the Trap',speaker:'Gray Hat',text:'You raise the shutter halfway and kill the lights. Old Zhou drives Gray Hat to his knees while Lin Xiao locks the front door. The man who was naming prices is now tied to the register, and the fake convoy outside is demanding an answer.',choices:[['Force him to reveal the real response code','Expose the fake channel'],['Take his supplies and lock him in the warehouse','Water +2 · Battery +1'],['Let Lin Xiao question him and answer through his radio','Requires saving the child']]});
    setNode('tunnel',{title:'Warehouse Passage · Deep Night',stamp:'21:15 / Broadcast Still Looping',speaker:'Ali',text:'The wall behind the shelves is hollow. Inside are sealed government supplies and a recorder still broadcasting the same distress call. The signal was designed to pull survivors into this district.',choices:[['Take the supplies and stop the recording','Food +3 · Water +2'],['Leave the supplies and record the frequency','Gain truth evidence']]});
    setNode('radio',{title:'Rooftop Radio · Midnight',stamp:'23:47 / Two Convoys Answer',speaker:'Radio',text:'A live voice finally breaks through: “East Line evacuation. Six-minute stop. Your coordinates leaked, and an armed convoy is also inbound.” Below, the clinic and store both switch on distress lights.',choices:[['Broadcast the clinic coordinates first','Requires enough Trust'],['Broadcast the store coordinates and save the supplies','Preserve your stockpile'],['Stay silent and lead everyone through the tunnel','Requires the hidden passage'],['Send false coordinates to draw away the armed convoy','Requires verified channel']]});
    nodes.ending.title='Chapter One Finale · Missing Signal';nodes.ending.stamp='00:03 / Coordinates Sent';nodes.ending.speaker='Narrator';nodes.ending.text=x=>{const f=x.flags;if(f.choseDecoy&&f.authenticated)return'You send the armed convoy toward the old looping coordinates. The real evacuation vehicle collects the clinic in darkness while Old Zhou locks the store for the last time. No one has to be left behind.';if(f.choseTunnel&&f.tunnel)return'You never answer the radio. Ali leads everyone through the underground warehouse as the red light goes dark behind you. The convoy finds nothing, and everyone survives.';if(f.choseClinic&&x.trust>=2)return'The evacuation vehicle reaches the clinic first. Lin Xiao carries the recovering child aboard while Old Zhou turns back to guard the store. You lose most of your supplies and gain a district willing to protect you.';if(f.choseStore)return'The vehicle stops at the store. You save the supplies and key, but the clinic light disappears in the rear-view mirror. The broadcast is never heard again.';return'Headlights appear in both directions. You were not prepared to save everyone, and this decision follows you into the next chapter.'};setChoices('ending',[['Replay Chapter One','Explore another route']]);

    setNode('c2_dawn',{title:'Night Two · Black Rain',stamp:'06:40 / Water Alert',speaker:'Lin Xiao',text:x=>'Every rain barrel contains black sediment. '+(x.flags.savedChild?'The child you saved is vomiting again, but Lin Xiao insists this is not an infection.':'The clinic calls again: the child who never received medicine is convulsing.')+' A soaked White Tower flyer is pinned to the store door.',choices:[['Seal all rainwater and find the rooftop source','Clean water temporarily disabled'],['Control the ration conflict in the courtyard first','Trust test']]});
    setNode('c2_roof',{title:'Rooftop Collection Area · Blue Glow',stamp:'07:25 / Drone Overhead',speaker:'Cheng Ye',text:'Cheng Ye opens the collector. Blue powder glows in the rain while a dark drone circles every lit building. The filter was cut recently. The saboteur was here last night.',choices:[['Track the drone toward the courtyard','Find the ground receiver'],['Confront Su Yan immediately','She knows White Tower protocol']]});
    setNode('c2_market',{title:'Residential Courtyard · Water Conflict',stamp:'11:10 / Three Barrels Left',speaker:'Lin Xiao',text:'Dozens crowd the ration barrels. Someone raised the allocation mark and pushed the elderly and children to the back. The drone slows whenever the shouting grows louder.',choices:[['Reveal the black-rain truth and ration by household','Trust +2'],['Hide the tracking risk and stabilize the crowd','Preserve order'],['Put Cheng Ye in front and force control','Requires Cheng Ye']]});
    setNode('c2_suyan',{title:'Flooded Underpass · Su Yan’s Decoy',stamp:'15:40 / Red Dot on the Wall',speaker:'Su Yan',text:x=>(x.flags.rescuedOffice?'The staff roster leads you into the drainage tunnel beneath the office building.':'The tracking signal disappears into a flooded underpass.')+(x.flags.outsmartedSuyan?' Su Yan no longer pretends to be injured, but still reaches toward you from beside the overturned truck.':' Su Yan kneels beside an overturned truck, deliberately pulling your attention toward her.')+' A trapped courier shakes his head on the right. Your light finds a remote at her leg and a nearly invisible wire across the water.',choices:[['Cut the wire and rescue the courier first','Save a life and seize the remote'],['Disable the tracker and force her to guide you','Requires finding the tracker'],['Use your pack as bait and trace the signal backward','Counter Energy +20']]});
    setNode('c2_pump',{title:'Underground Pump Station · L-17',stamp:'19:30 / Water Rising',speaker:'Ali',text:'A passage behind the store shelves reaches an old pump station marked L-17. Your missing sister signed the final maintenance log. The main pump is dead, and contaminated water is flowing back into the clean line.',choices:[['Restart the pump and isolate the contamination','Requires powering the valve'],['Seal the pipe manually and preserve existing water','Lose the pump station'],['Trace your sister’s verification code through the logs','Gain core evidence']]});
    setNode('c2_choice',{title:'Tracking Tower · Night Two Finale',stamp:'23:12 / White Tower 18 Minutes Away',speaker:'Ali',text:'The repaired pump raises the rooftop antenna. Its screen reads: L-17, 37 survivors, one medic, one engineer. Your sister’s code is waiting for input while White Tower vehicles turn toward the district.',choices:[['Destroy the antenna and vanish from the map','Safest choice'],['Enter your sister’s code and broadcast the truth','Requires code and tracker'],['Forge coordinates for two hundred people at the empty pump station','Requires Su Yan’s intel or reverse tracking']]});
    nodes.c2_end.title='Chapter Two Finale · Poison Rain';nodes.c2_end.stamp='23:47 / Second Key';nodes.c2_end.speaker='Narrator';nodes.c2_end.text=x=>x.flags.c2Hijack?'You enter your sister’s code. Every lighthouse in the city reveals White Tower’s recovery list, and unknown channels answer: “We see it.” The second shutdown key unlocks.':x.flags.c2Decoy?'White Tower redirects to the abandoned pump station. Su Yan hears them fail at the false coordinates and laughs honestly for the first time. The district gains one night, but the tracking network remains active.':'The antenna snaps in the rain. The drones lose the district, but your sister’s verification code burns with the circuit.';

    if(typeof directorCases!=='undefined')Object.assign(directorCases,{
      dawn:{question:'Why did Su Yan know exactly where to find this store?',options:[['She already had the inventory and rooftop-key intelligence',true,'The wet fingerprint marks only the missing medicine, and the key has fresh antenna paint. She came with information.'],['She randomly searched for any lit store',false,'A random arrival does not explain the precise medicine location or recently used key.'],['She hid inside the store all night',false,'The lock and rain trail both begin outside.']]},
      alley:{question:'What is Su Yan actually controlling when she reaches toward you?',options:[['Your step onto a noise alarm that exposes the street',true,'The weak wire, empty cans and single dry foothold all point to a location alarm.'],['She needs your strength to cross deep water',false,'She is standing on the only safe foothold.'],['She is trying to steal the medical bag',false,'Her hand controls your footing, not the bag.']]},
      clinic:{question:'Where did the 23:47 broadcast clue most likely originate?',options:[['Someone took information from the clinic, then carried the key to the roof',true,'The outward writing, round-trip footprints and red paint connect clinic, store and roof.'],['Lin Xiao broadcast directly from the ward',false,'The ward has writing but no transmitter, and the footprints leave the clinic.'],['The time is unrelated coincidence',false,'The time and footprints form a repeatable link.']]},
      diagnose:{question:'What do the black particles and closed route imply?',options:[['The contaminant reacts to metal infrastructure and uses water to mark occupied buildings',true,'The particles bind to metal, while the route links antenna, rainwater and pump station.'],['A virus magnetized the child’s blood',false,'The particles appear in water containers, not the body.'],['The pump station is only a shelter',false,'The route also reaches the rooftop transmitter.']]},
      search:{question:'Who is controlling the route through the key, paint and unmarked patrol?',options:[['Someone is using rooftop equipment and a fake patrol to sort survivors',true,'The key reached the antenna, and the vehicle follows the same route without official markings.'],['Old Zhou stole a vehicle for food',false,'That cannot explain the seven-second sweep.'],['A real rescue unit is containing an infection',false,'A real unit would not erase its number or use a store warehouse key.']]}
    });
    if(typeof evidenceOperations!=='undefined')Object.assign(evidenceOperations,{ledger:['Lift the waterproof film','Wipe the water stain sideways'],lock:['Insert the key','Turn it slowly'],wire:['Clamp the wire','Cut and secure the end'],cleanboot:['Move the loose brick','Pull out the hidden line'],footprint:['Turn on the UV lamp','Scan along the print'],window:['Clear the condensation','Trace the writing direction'],bottle:['Bring the magnet to the bottom','Move it and watch the particles'],mapmark:['Unfold the map','Align the three red routes'],key:['Open the toolbox latch','Rotate the key and inspect the teeth'],siren:['Connect the frequency detector','Calibrate the light interval'],cable:['Strip the cable','Align the broken copper'],badge:['Clean the badge','Read the rear serial number'],shutter:['Listen against the shutter','Match the knock pattern'],backdoor:['Move the boxes','Pull the hidden bolt'],radio:['Switch monitoring bands','Match the background noise'],redlamp:['Block ambient reflection','Measure the flash interval']});

    if(typeof stageActors!=='undefined')Object.assign(stageActors,{dawn:{...stageActors.dawn,label:'Make Su Yan explain herself'},clinic:{...stageActors.clinic,label:'Talk to Lin Xiao'},diagnose:{...stageActors.diagnose,label:'Take the water sample from Ali'},search:{...stageActors.search,label:'Talk to Old Zhou'},alley:{...stageActors.alley,label:'Watch Su Yan’s hand and the water'},garage:{...stageActors.garage,label:'Work with Cheng Ye'},radio:{...stageActors.radio,label:'Talk to Ali'},c2_dawn:{...stageActors.c2_dawn,label:'Question Lin Xiao'},c2_roof:{...stageActors.c2_roof,label:'Question Cheng Ye'},c2_market:{...stageActors.c2_market,label:'Help Lin Xiao'},c2_suyan:{...stageActors.c2_suyan,label:'Watch Su Yan’s hidden hand'},c2_pump:{...stageActors.c2_pump,label:'Question Ali'},c2_choice:{...stageActors.c2_choice,label:'Question Ali'}});

    if(typeof routeScenes!=='undefined'){
      const routes={
        'dawn>alley':['Outside the Shutter · Ambulance Alley','She leads you to an abandoned ambulance instead of the clinic. The warning light feels warm, but a patrol beam is closing in.','Inspect the line in the water','Follow her footsteps along the wall','Take her hand and cross','You avoid the wire and find the empty cans marking targets for the patrol.','Her hand is steady, but your shoe touches the wire on the final step.'],
        'alley>clinic':['Clinic Side Door · Patrol Beam','After the wire is cut, Su Yan stops taking detours. Lin Xiao waits behind a narrow opening while red light moves across the wall.','Watch the red-light pause','Wait, then knock three times','Throw the ambulance beacon into the street','Lin Xiao recognizes the signal and opens the door during the seven-second gap.','The patrol turns toward the rolling beacon. You gain time but expose activity near the ambulance.'],
        'search>garage':['Outside the Blockade · Workshop Door','An unmarked vehicle seals the main road. Someone is holding a half-fallen shutter while the motor burns.','Inspect the winch','Cut the overheating power first','Rush under the shutter','You find the cut cable and manual brake, buying the people inside ten seconds.','You slide through oil as the shutter slams behind you.'],
        'garage>radio':['Black Stairwell · Rooftop Access','The last two floors have no power. Radio noise comes from above while metal impacts echo below.','Listen to the echo','Climb in darkness along the wall','Turn on the flashlight and rush','You avoid a broken stair and find Ali calibrating the antenna.','The flashlight exposes your position, but you gain thirty seconds.'],
        'c2_dawn>c2_roof':['Stairs in the Black Rain','Rain barrels sit outside every apartment. The higher you climb, the brighter the blue glow becomes.','Check the water marks','Close the rain pipes on the way up','Reach the rooftop source first','You shut three intake valves and slow the spread.','You reach the roof first, but someone downstairs has already drunk the rainwater.'],
        'c2_dawn>c2_market':['Outside the Courtyard · Seventh Second','People crowd the ration barrels. A drone slows over the loudest conflict every seven seconds.','Count the drone interval','Enter in dark groups','Climb the tank and control the crowd','You move the elderly and children through darkness, leaving only scattered heat signatures.','Everyone sees you. So does the drone hovering for the full seven seconds.'],
        'c2_roof>c2_market':['Following the Drone Down','The drone shadow falls over the three remaining barrels. A freshly altered ration line marks the ground.','Check the chalk dust','Reach Lin Xiao through the side door','Push through to the barrels','You catch the person repeatedly changing the line.','You stop the fight but become the drone’s clearest target.'],
        'c2_roof>c2_suyan':['Under the Overpass · Help Signal','The tracker enters a flooded underpass. Su Yan reaches from beside an overturned truck while a trapped courier shakes his head.','Look for the line across the water','Inspect beside her along the wall','Pull her to her feet','Your light reveals the submerged wire and the remote in her hidden hand.','She rises using your hand and pushes the wire toward your next step.'],
        'c2_market>c2_suyan':['Blackout Office · Two Sides of the Gate','Xu Man crosses the broken gate and offers an executive keycard. Behind her, seventeen workers are locked upstairs.','Verify the keycard floors','Check the card before crossing','Take her hand and jump the gate','The card opens only the executive stairwell. Her “everyone” route is a lie.','You cross quickly, and the fire doors protecting ordinary staff begin to lock.'],
        'c2_suyan>c2_pump':['Drainage Shaft · Backflow','Su Yan’s coordinates lead to the old pump station. Water rises below while Ali warns you away from the yellow platform.','Light the valve gauge','Descend along the maintenance chain','Jump the rail to the platform','You find a tensioned chain and the L-17 backup entrance.','You land first, but the rail falls into the water and seals the return route.'],
        'c2_pump>c2_choice':['Maintenance Shaft · Antenna Rising','The pump restarts and raises the antenna. White Tower vehicles are three streets away while the screen counts the district.','Read the rotating red light','Remove identity tags on the way up','Carry the code straight to the roof','You remove three tags and reduce the registered population from forty to thirty-seven.','You reach the transmitter before lock-in, but everyone below remains listed.']
      };
      Object.entries(routes).forEach(([key,values])=>{const r=routeScenes[key];if(!r)return;[r.title,r.text,r.scan,r.safe,r.bold,r.safeText,r.boldText]=values});
      const office=routeScenes['c2_market>c2_suyan'];if(office?.followup){office.followup.text='The alarm gives you twenty seconds. Xu Man wants you to take the card, while Zheng Kai points his light toward the people calling upstairs.';const a=office.followup.choices[0],b=office.followup.choices[1];Object.assign(a,{label:'Return and unlock the staff floors',hint:'Save seventeen people, lose tracking time',result:'You and Zheng Kai hold the fire door until Xu Man hands over the real roster. By the time everyone reaches the ground floor, the drone has moved on.',heading:'You Choose the Rescue'});a.evidence[1]='Locked-Floor Roster';Object.assign(b,{label:'Take the executive keycard and keep tracking',hint:'Gain time and a White Tower entry route',result:'You take the card and follow Xu Man through the executive stairwell. The knocking remains above, but the card opens White Tower contractor access.',heading:'You Take the Shortcut'});b.evidence[1]='White Tower Executive Keycard'}
    }
    if(typeof tutorialCopy!=='undefined')Object.assign(tutorialCopy,{1:['Hear Them Out','Tap the person in the scene. Dialogue reveals investigation leads and affects later decisions.'],2:['Search Suspicious Areas','Tap the gold-marked areas to inspect evidence.'],3:['Inspect It Yourself','Complete the inspection action, then move the slider to reveal the detail.'],4:['Complete the Evidence','Investigate the second anomaly, then open Review Evidence to make a deduction.'],5:['Act on Your Deduction','Choose the conclusion best supported by the evidence, then select your route.']});
    if(typeof endingCatalog!=='undefined')endingCatalog.splice(0,endingCatalog.length,['decoy','Ghost Manifest','Send the hunters after a phantom while every survivor escapes.'],['tunnel','After the Lights Go Out','Everyone leaves underground and disappears from the city.'],['clinic','The District Survives','Trade supplies for a community willing to protect one another.'],['store','Leave Fully Stocked','Save the shelves and leave the clinic in darkness.'],['lost','Wrong Coordinates','Poor preparation turns every decision into abandonment.']);
    if(typeof chainRecipes!=='undefined'){const data=[['The Key Stayed Inside','The lock was intact but the inventory was altered. The thief knew the warehouse.','Counter Energy +25'],['23:47 Was Not a Distress Time','The rooftop paint and window time form a deliberate action signal.','Trust +1 · Counter Energy +25'],['Gray Hat Was the Guide','Old Zhou’s key and the unmarked patrol reveal the fake convoy route.','Counter Route Unlocked'],['The Hunters Exposed Their Channel','The looping tape and armed convoy share the same background noise.','Final Counter Unlocked']];chainRecipes.forEach((recipe,index)=>{recipe.title=data[index][0];recipe.detail=data[index][1];recipe.reward=data[index][2]})}
    if(typeof endingInfo==='function')endingInfo=function(){if(s.flags.choseDecoy&&s.flags.authenticated)return{id:'decoy',title:'Ghost Manifest',desc:'You send the enemy after a phantom while the living escape.'};if(s.flags.choseTunnel&&s.flags.tunnel)return{id:'tunnel',title:'After the Lights Go Out',desc:'Everyone leaves underground without revealing where they went.'};if(s.flags.choseClinic&&s.trust>=2)return{id:'clinic',title:'The District Survives',desc:'You sacrifice supplies for a community that protects its own.'};if(s.flags.choseStore)return{id:'store',title:'Leave Fully Stocked',desc:'The shelves survive. The clinic light does not.'};return{id:'lost',title:'Wrong Coordinates',desc:'Without preparation, every choice becomes abandonment.'}};
    if(typeof endingLines==='function')endingLines=function(){return[s.flags.savedChild?'The clinic child survived.':'The clinic never received enough medicine and water.',s.flags.truth||s.flags.authenticated?'You uncovered the truth behind the looping broadcast.':'The truth behind the broadcast remains incomplete.',s.relations.zhou>0?'Old Zhou will continue with you.':'Old Zhou did not become your ally.']};
    if(typeof chapter2EndingInfo==='function')chapter2EndingInfo=function(){return s.flags.c2Hijack?['The Whole City Saw It','You turned White Tower’s marks into public evidence.']:s.flags.c2Decoy?['The Empty Pump Decoy','The enemy follows a false population while the district gains time.']:['Disappear from the Map','You save the district but burn part of the truth.']};

    if(s?.evidence)Object.keys(s.evidence).forEach(id=>{if(evidenceNames[id])s.evidence[id]=evidenceNames[id]});
    if(s?.echo&&/[\u4e00-\u9fff]/.test(s.echo))s.echo='';
  }

  window.LastLightLocale={lang:language,isEnglish:english,t:translateText,pick:(zh,en)=>english?en:zh,set(next){localStorage.setItem('lastLightLanguage',next);location.reload()}};
  if(english)applyEnglishContent();

  const languageButton=document.createElement('button');
  languageButton.id='languageToggle';languageButton.className='language-toggle';languageButton.textContent=english?'中文':'EN';languageButton.title=english?'Switch to Chinese':'切换到英语';
  languageButton.onclick=()=>window.LastLightLocale.set(english?'zh':'en');
  const tools=typeof headerTools!=='undefined'?headerTools:document.querySelector('.header-tools');
  if(tools)tools.appendChild(languageButton);else document.querySelector('#scene>header')?.appendChild(languageButton);

  const menuLanguage=document.createElement('button');menuLanguage.className='menu-language';menuLanguage.textContent=english?'中文版本':'English Version';menuLanguage.onclick=languageButton.onclick;menu?.querySelector('.start-card')?.appendChild(menuLanguage);

  if(english){translateDom(document.body);const observer=new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(added=>{if(added.nodeType===Node.TEXT_NODE){const next=translateText(added.nodeValue);if(next!==added.nodeValue)added.nodeValue=next}else if(added.nodeType===Node.ELEMENT_NODE)translateDom(added)})));observer.observe(document.body,{childList:true,subtree:true,characterData:true});setTimeout(()=>{if(typeof render==='function')render();translateDom(document.body)},0)}
})();
